### ISSUE TITLE
Username vs email + hashing confusion

### ISSUE THREAD

**Issue by larsivi** [accounts-js/accounts#1005]
# Bug report
Difficult to set up email-as-username

## Describe the bug
I tried to setup my system to have emails as username (this seems to generally be very common around the Internets), but if I created my users with email and password (all my users are authoratively created on the server), then I got an authentication problem as the only way I was able to send the credentials from the client was as a { user: { username }, password: "foo" } type of object.

When this object enters the toUsernameOrEmail function in accounts-password, it enters the { ...user } variant, which then results in only the username parameter being valid (user is not part of the destructured object, so it is undefined). The function then skips the check for email, and just returns the input parameters, so just username being defined. So in the continuance, findUserByUsername is used, and the user isn't found.

I then tried to store the email in both username and email, and just in username, both both these failed because there turned out to be a default username validator that don't accept usernames-as-emails.

In the end I could workaround this by creating my own validateUsername that allowed emails.

## To Reproduce

See above

## Expected behavior

I expected to able to log in using just an email.

## Screenshots

N/A

## System information

- Version of accounts-js: [e.g. 0.0.27]

## Additional context

I was momentarily confused by the hashing part, as I thought it failed there for a moment. It turns out that client hashing the password is not a very good idea when the user is created on the server if the password isn't hashed the same way there :)

So I think the fix here is mostly about documentation, but also that the toUsernameOrEmail function probably needs to do things somewhat different in the case where user is destructured.

**Comment by pradel** [comment]
@larsivi I am a bit confused, if you use the email as a username, why would you use a username at all? I guess just using the email and no username should be easier in such case or did I miss something?

> I was momentarily confused by the hashing part, as I thought it failed there for a moment. It turns out that client hashing the password is not a very good idea when the user is created on the server if the password isn't hashed the same way there :)

Client-side hashing is disabled by default in the latest versions, are you using an old version where the default in still enabled?

**Comment by larsivi** [comment]
So I think we cleared up this on the slack, but the main issue was that I didn't fully understand how to use email to login, partially because I also was unfamiliar with the  `{ username }` to mean `{ username: username }`. Looking at it now, I'm not clear on where anything should be fixed, so closing this issue.
