### ISSUE TITLE
RFC: AccountsJS + Oauth + Packages + Docs

### ISSUE THREAD

**Issue by agustif** [accounts-js/accounts#1031]
@nsine was kind enough to share his work implementing Google oauth with Accounts on #961 
Also related to: #1026 #875 

I want to continue @nsine's work in order to complete as much as possible the AccountsJS oauth ecosystem and docs.

> This PR adds very rough example of how to use accounts-js OAuth to login/register with Google.
> Opening it (as a draft, as don't have too much time atm to polish it) mostly because @agustif asked some help on this and may be can be useful for others.
> 
> Feel free to pick this up and implement complete example if someone has time/motivation. This can serve as a good base to start from 🙂.
> What has to be done from my PoV to add this as an official example:
> 
> * [ ]  make nice styling
> * [ ]  Add other examples apart from google (e.g. OOTB twitter, instagram)
> * [ ]  Add error handling
> * [ ]  Add some readme to oauth package and reference
> * [ ]  Add page where we can link oauth providers to existing accounts (afaik @agustif already tried to do sth like this)
> 
> **To make this work:**
> 
> * fill `examples/react-rest-typescript/.env.development` with valid google client id and callback url
> * create `.env` file in `examples/rest-express-typescript` folder with variables from `.env.example` in same folder
> 
> Hope that helps!

## Oauth adapters
* [x] Instagram (Already on packages)
* [x] Twitter (Already on packages)
* [x] Google by @nsine 
* [x] Facebook by @agustif 
* [ ] NextCloud by @TeNNoX 
* [ ] GitHub

## Oauth example
@nsine extended the rest examples, should I continue this and push to the rest examples adding oauth, or fork with a new example folders for oauth cllient and server? 

Also planning on doing GraphQL too, I think @nsine uses it and can help me if needed!
## Please comment!
This is a request for comments, so any feedback idea will be greatly appreciated.

**Comment by pradel** [comment]
@agustif I think that adding it to the current rest example is the easiest way for now :)

**Comment by TeNNoX** [comment]
@agustif @nsine Ready for review: https://github.com/accounts-js/accounts/pull/1080

:sunglasses:

**Comment by gezquinndesign** [comment]
Are there any examples of how to implement oauth-facebook and oauth-twitter for graphql-transport?  I've managed to get the google one working using @nsine's great example - Just wondering if there's anything similar for twitter and facebook? Any help would be very much appreciated.  Thanks
