### ISSUE TITLE
Typescript issues with context from request (express, apollo-graphql)

### ISSUE THREAD

**Issue by larsivi** [accounts-js/accounts#1034]
# Bug report

## Describe the bug
I have a setup with apollo-graphql and express, and I need to do some stuff with the context after accounts is done with it.
I used to have
"let context = await accounts.context(req);
if (context.session.body.blah == 'foo') { ... do something } ",
but now I have stricted up my typescript and I don't actually know what type context should be such that I am able to access session and body.
ModuleContext<AccountsModuleContext> is not enough at least.

I have created my own type interface hierarchy to represent what I need from this object, but I'd prefer if I could either get this directly from the API, or at minimal from documentation. 

## System information

- Version of accounts-js: [e.g. 0.0.27]

## Additional context

Reposted from forum where it was suggested to fix this with generics.

**Comment by agustif** [comment]
https://www.accountsjs.com/docs/api/graphql-api/interfaces/accountsmodulecontext/

`import { AccountsModuleContext } from '@accounts/graphql-api'

Not sure if this is what you need but it might help.
