### ISSUE TITLE
this.db.findUserByEmail is not a function

### ISSUE THREAD

**Issue by awatson1978** [accounts-js/accounts#1039]
# Bug report

Hello, 
Thank you for all the hard work that's gone into accounts-js.  Hope everyone is doing well in all this pandemic craziness.  

So, I'm getting a pair of errors that I can't debug, while trying to sign up a new user.  On the client I'm getting the following in the Snackbar: 

```
this.db.findUserByEmail is not a function
``` 

And in the browser console:

```
POST http://localhost:4000/accounts/password/register 400 (Bad Request)
```

## Describe the bug

_client_
```js
import { AccountsClient } from '@accounts/client';
import { AccountsClientPassword } from '@accounts/client-password';
import { RestClient } from '@accounts/rest-client';

const accountsRest = new RestClient({
  apiHost: 'http://localhost:4000',
  rootPath: '/accounts',
});

const accountsClient = new AccountsClient({}, accountsRest);
const accountsPassword = new AccountsClientPassword(accountsClient);

onSubmit: async function(values, { setSubmitting }){
  try {
    await accountsPassword.createUser({
      givenName: values.givenName,
      familyName: values.familyName,
      email: values.email,
      password: values.password,
    });

  } catch (error) {
    setError(error.message);
    setSubmitting(false);
  }
}
```

_server_
```js
import mongoose from 'mongoose';

import { AccountsServer, ServerHooks } from '@accounts/server';
import { AccountsPassword } from '@accounts/password';
import accountsExpress, { userLoader } from '@accounts/rest-express';

mongoose.connect(process.env.MONGO_URL || 'mongodb://localhost:27017/meteor');
const db = mongoose.connection;
const app = express();

const accountsPassword = new AccountsPassword({
  // This option is called when a new user create an account
  // Inside we can apply our logic to validate the user fields
  validateNewUser: function(user){
    console.log("AccountsServer: Validating new user.")
    // For example we can allow only some kind of emails
    if (user.email.endsWith('.xyz')) {
      throw new Error('Invalid email');
    }
    return user;
  },
});

const accountsServer = new AccountsServer(
  {
    db: mongoose.connection,
    tokenSecret: Random.secret(),
  },
  {
    password: accountsPassword
  }
);

app.use(accountsExpress(accountsServer));

app.post('/accounts/password/register', userLoader(accountsServer), async function (req, res){
  let body = get(req, 'body');
  console.log('body', 'body')
  res.json(true);
});

app.listen(4000, function(){
  console.log('AccountsServer: listening on port 4000');
});

```

## Expected behavior

I'd expect that a new user would be generated.  Or at the very least, the `validateNewUser` function would be called.

If anybody has some thoughts on why `accountsPassword.createUser()` isn't triggering the `validateNewUser()` function, and why `/accounts/password/register` doesn't seem to exist, I'd be keen to hear them!

Thanks in advance!

**Comment by pradel** [comment]
Hey @awatson1978 looks like you are not setting the database correctly you have to use `@accounts/mongo`, see https://www.accountsjs.com/docs/databases/mongo to see how to set up it.

**Comment by awatson1978** [comment]
Ah!  Very good.  That did the trick.  For others who are researching the issue, I used the following:

```js
  mongoose.connect(process.env.MONGO_URL);

  const db = mongoose.connection;
  const accountsMongo = new Mongo(db, {
    // options
  });
  const accountsServer = new AccountsServer(
    {
      db: accountsMongo,
      tokenSecret: Random.secret(),
    },
    {
      password: accountsPassword
    }
  );

```

It's probably worth updating the `rest-express-typescript` example so that it matches the documentation.
https://github.com/accounts-js/accounts/blob/master/examples/rest-express-typescript/src/index.ts#L8-L53   

Thanks for the help!  My issue is solved.  Should I close the ticket out or leave it open till the example gets updated?

**Comment by pradel** [comment]
@awatson1978 the example is showing the good approach `db: new MongoDBInterface(db),` or am I missing something? 🤔

**Comment by awatson1978** [comment]
Mmmm, I haven't been able to get the `MongoDBInterface` syntax working.  

Although a disclaimer:  I'm using ES6/EcmaScript, and not using the TypeScript transpiler.  So most of my code enforces types with `Foo.propTypes` rather than inline types.  

But for whatever reason, `MongoDBInterface` doesn't work for me.

**Comment by pradel** [comment]
Okay, I will leave the issue open and fix the example, thanks!
