### ISSUE TITLE
Emit server hooks with "await" to guarantee all code in hooks is executed before user got a response from server

### ISSUE THREAD

**Issue by nsine** [accounts-js/accounts#1062]
# Feature request

## Is your feature request related to a problem? Please describe.

Hey account-js community! I have a quick question regarding how server hooks are supposed to work. I tried to move some post-registration logic (after creating a user i have to create some more instances) from our custom gql mutation to `CreateUserSuccess` server hook. But i noticed that calling hooks works differently in different places. When registering user using oauth - it's called with `await` https://github.com/accounts-js/accounts/blob/master/packages/oauth/src/accounts-oauth.ts#L55 which according to `emittery` docs https://www.npmjs.com/package/emittery#emiteventname-data will wait until all listeners are executed.
I was super happy about this behavior but then i noticed that when creating user through password module the hook is emitted without `await` https://github.com/accounts-js/accounts/blob/master/packages/password/src/accounts-password.ts#L653 which doesn't allow me to use this, as expect that all required related models are created for sure after the mutation is executed, but with async hooks i cannot ensure that. This also causes bigger issues with unit tests. 

## Describe the solution you'd like

So my proposal would be to align hooks usage in different places and i think they should be called with `await` everywhere as it's a good place to do extra logic once new user is registered, but at the same time you probably want to guarantee all this logic is done until response is returned from the server, not "at some time in future"

Please let me know wdyt and i can create a PR for this

**Comment by pradel** [comment]
That's a really good point, we should definitely have the same logic for the hooks I think. The idea of not awaiting this particular hook was to send back the request earlier to the user. But at the same time, this wouldn't work in a serverless environment. If we change the behaviour to await, the user can decide to use defer in his own code or not.
We need to be careful with these changes since it will be a breaking change :)

**Comment by nsine** [comment]
@pradel my argument to `await`ing it would be
> it's a good place to do extra logic once new user is registered, but at the same time you probably want to guarantee all this logic is done until response is returned from the server, not "at some time in future"

^ from what i wrote in the description
I think adding `await` won't be a breaking change

**Comment by pradel** [comment]
It will be a breaking change in the sense that if some users have some long-running process already setup in this hook, it will block the request with this change.

**Comment by nsine** [comment]
@pradel okay that makes sense
So do you think we should proceed on that? May be adding some flag like `awaitForHooksCalled: true` in config?

**Comment by pradel** [comment]
> So do you think we should proceed on that?

Definitely 👍 

> May be adding some flag like awaitForHooksCalled: true in config?

As this is something you can do in your code I am not sure it's really needed tbh.

**Comment by nsine** [comment]
> As this is something you can do in your code

not really 😅

I can't guarantee that some extra models created inside `CreateUserSuccess` hook are created before response is returned to client because it will happen "at some point"

Of course i can overwrite a default `createUser` mutation (which i already do now) and add some extra code here, but i'm not really sure how to do the same when user is registered during OAuth. May be i miss some easy solution? Would be nice if you share some ideas 🙏

**Comment by pradel** [comment]
I mean after the `await` behavior is changed, the user will be able to decide to block the request or defer the execution in the hook :)

**Comment by nsine** [comment]
ah i got what you mean
misunderstood you initially 🙂

That's correct then. Do you want me to submit a PR with this change?

**Comment by pradel** [comment]
That would be great, thanks 🙏

**Comment by nsine** [comment]
@pradel here is the PR https://github.com/accounts-js/accounts/pull/1068
not sure if you've seen that 😅
