### ISSUE TITLE
Class constructor SchemaDirectiveVisitor cannot be invoked without 'new'  at new AuthenticatedDirective in nextjs

### ISSUE THREAD

**Issue by edw19** [accounts-js/accounts#1091]
when using the @auth directive in queries I get the message. Class constructor SchemaDirectiveVisitor cannot be invoked without 'new' at new AuthenticatedDirective. I am using nextjs 10 node 14, apollo-server-micro

![image](https://user-images.githubusercontent.com/47750859/104772324-3b0b0200-5741-11eb-823e-5ec239af6e23.png)

**Comment by pradel** [comment]
@edw19 can you provide a repository showing the error so I can have a look?

**Comment by pradel** [comment]
@edw19 I actually found the issue, will create a fix for it today :)

**Comment by pradel** [comment]
Published a fix for this in v0.31.1
