### ISSUE TITLE
Migrating from a Meteor.js App to a Nodejs app that uses accountsjs

### ISSUE THREAD

**Issue by acomito** [accounts-js/accounts#1103]
I know there is a way to make your meteor app use accountsjs, is there a way to use my old mongodb with a node app that uses accountsjs?

The main issue so far is that meteor users have string _ids and I think accountsjs expects ObjectIds

**Comment by pradel** [comment]
When setting up the @accounts/mongo package you can use this option https://www.accountsjs.com/docs/api/database-mongo/interfaces/accountsmongooptions#optional-convertuseridtomongoobjectid to tell the package to use strings instead of objectIds for the user documents.

**Comment by acomito** [comment]
Nice. Thanks @pradel 

The other thing I'm running into is, I think, my auth secret for meteor was different. I don't even think I set an auth secret, so not sure how I'll be able to track down which one meteor was using.

**Comment by pradel** [comment]
The secret is just used to create the sessions, not using the same won't actually change something as the users will be logged out anyway.
