### ISSUE TITLE
What's the actual state of the project ?

### ISSUE THREAD

**Issue by Aetherall** [accounts-js/accounts#111]
Hi! I'm creating a small framework on top of apollo, express, mongodb, and react/redux and I wanted to know how difficult it would be, considering the actual stage of the project, to achieve mechanisms such as

- providers auth
- token expiration and refresh
- password update
- providers linking

**Comment by davidyaha** [comment]
Hey @Aetherall!
Thank you for the interest in this project!

You can go over to #107 for current stages of our next big release that will feature:
- Typescript all around
- Modular authorization strategies including oauth providers (auth and linking)

For the current stage of the project, it already has a solution for local strategy (password based) and it currently handles password update and including forgot password emails, enrollement email ("Set your password") and email verification.
We also have JWT based token system in place which will be scoped as "session management" after our change is complete.

Hopes this helped explain the current stage we are at.

If you'd like to help advance us further, please go through the open PRs liseted under #107 and try those out on your own. We need feedback, and also if you would like to contribute, I've just pushed the current work of refactoring into a new WIP PR #112.

**Comment by Aetherall** [comment]
I'll try those on the next week !
