### ISSUE TITLE
Using destructuring instead of Immutable

### ISSUE THREAD

**Issue by Aetherall** [accounts-js/accounts#113]
Immutable js forces the use of state.get and state.set, we can achieve the same thing with destructuring without making the store mixing Map and Objects right?

**Comment by davidyaha** [comment]
I am not sure I understand how destructuring is a replacement to immutables? 
Also, the decision to use immutables for the client state is a bit obsolete and we would like to redesign the client store parts of this package.
How would you think we should have it?

**Comment by Aetherall** [comment]
It's because we can do newState = { ...state } to clone an object while keeping the code clean
If we use destructuring we will keep the immutability
By client store you mean the accountsJs redux store ?
It's a good thing that it's redux, because it permit to keep the package consistant with the rest of the app

My main problem is that I would keep the token part somehow external, so we could disable it on the client and change the transport for them on th server

Maybe we should compose the reducers and methods accordingly to params in the config passed to the client ?
