### ISSUE TITLE
[ Contributing ] Can you share your development workspace ?

### ISSUE THREAD

**Issue by Aetherall** [accounts-js/accounts#114]
Hi ! 
I'm using accounts js for a month now and I am wanting to contribute ! :)

I want to add the ability to store tokens in either cookies, headers, body or many of them, by adding new packages

to be honest, it will be the first time between me and typescript and I feel a little unconfortable :')

That's why I'm asking for active devs of this project to share their dev workspace, so I can study/use it and go on solid basis

I'm using VSCode so if you made any kind of awesome setup please add the .vscode folder

Thanks !

**Comment by pradel** [comment]
@Aetherall can we close this one?

**Comment by Aetherall** [comment]
Sure, I currently do as david said, all packages in a single folder

**Comment by davidyaha** [comment]
Excellent!
