### ISSUE TITLE
Upgrade graphql-modules to current version.

### ISSUE THREAD

**Issue by Akarshit** [accounts-js/accounts#1140]
# Feature request
Accounts-js depends on graphql-modules/core and graphql-modules/di both of which are no longer maintained and have security vulnerabilities. We should update to graphql-modules v1  as soon as possible.

**Comment by pradel** [comment]
@Akarshit there is no patch version for the security issue and we need to upgrade directly to v1?
If yes we already have an issue for this here :) https://github.com/accounts-js/accounts/issues/1079

**Comment by Akarshit** [comment]
Yeah I didn't see any patch version. We are using the "latest legacy" version.

**Comment by pradel** [comment]
Okay, then I will close this one in favor of https://github.com/accounts-js/accounts/issues/1079
