### ISSUE TITLE
ResumeSession without fetch user from databse

### ISSUE THREAD

**Issue by brightchip** [accounts-js/accounts#1146]
https://github.com/accounts-js/accounts/blob/14ce077498ea8d89a26ff73ed051885409cb9200/packages/server/src/accounts-server.ts#L481

https://github.com/accounts-js/accounts/blob/14ce077498ea8d89a26ff73ed051885409cb9200/packages/server/src/accounts-server.ts#L514

Can you add an  option to return only userId from JWT without go through database for user . 
` public async resumeSession(accessToken: string, jwtOnly: Boolean): Promise<CustomUser> { `

**Comment by darkbasic** [comment]
This is already implemented: https://github.com/accounts-js/accounts/blob/9270f87ad761995e8313d3a4eabdfdce2cb47b50/packages/server/src/accounts-server.ts#L535

Please look at the microservices example.
