### ISSUE TITLE
Accountsjs mongo package not respecting collection name

### ISSUE THREAD

**Issue by Adel-ak** [accounts-js/accounts#1155]
# Bug report

## Describe the bug

I've created to intense of mongo one has the default collection name `user` the other `drivers` and when a user is created with `drivers` it ends up creating in `user` collection.

## To Reproduce

```
const userDB = new Mongo(db, {
    collectionName: 'users',
    convertUserIdToMongoObjectId: true,
  });

  const driverDB = new Mongo(db, {
    collectionName: 'drivers',
    convertUserIdToMongoObjectId: true,
  });

  await Promise.all([driverDB.setupIndexes(), userDB.setupIndexes()]);

  await userDB.createUser({
    email: 'user@user.com',
    password: 'userDemo123'
  });

  await driverDB.createUser({
    email: 'user@user.com',
    password: 'userDemo123'
  });
```

## Expected behavior

It should create the users in the given collection name

## Screenshots

Nop

## System information

```
    "@accounts/graphql-api": "^0.33.0",
    "@accounts/mongo": "^0.33.0",
    "@accounts/password": "^0.32.0",
    "@accounts/server": "^0.33.0",
```

## Additional context

I've dug into to the model package and It seems like in the file `node_modules/@accounts/mongo/lib/mongo.js` we need to pass a key of `userCollectionName` with the collection name to
```
this.servicePassword = new mongo_password_1.MongoServicePassword({ ...this.options, userCollectionName: this.options.collectionName, database: this.db });
this.serviceMagicLink = new mongo_magic_link_1.MongoServiceMagicLink({
            ...this.options,
            userCollectionName: this.options.collectionName,
            database: this.db,
        });
```

Once i added them they are working fine

**Comment by Adel-ak** [comment]
Should i make a PR ?

**Comment by pradel** [comment]
Good catch, pr welcome for the fix :)

**Comment by Adel-ak** [comment]
@pradel I can make a PR but im not sure how i would write a test for it

**Comment by pradel** [comment]
It's fine to just have the fix for now :)

**Comment by Adel-ak** [comment]
Cool created a PR @pradel
