### ISSUE TITLE
Change coveralls for codecov?

### ISSUE THREAD

**Issue by pradel** [accounts-js/accounts#118]
I think https://codecov.io/ offer a better alternative to coveralls.

**Comment by davidyaha** [comment]
I use codecov on other project that I have, I think it's solid enough. It has two coverage diffs that it does and I am not sure why this is, but one of those always fails..

What features does codecov offer over coveralls?
We do already have some coverage service so what is the reason to change?

**Comment by pradel** [comment]
Coveralls will create a comment on each commit for a pr and codecov will just edit the first comment to reflect the latest changes.
Also the comments are more detailed about what's changed.
And I remember we had a lot of trouble with coveralls.

**Comment by davidyaha** [comment]
Hmm, okay I have no objection there :)

**Comment by pradel** [comment]
@TimMikeladze @dotansimha ?
