### ISSUE TITLE
error TS2724: '"bson"' has no exported member named 'ObjectID'. Did you mean 'ObjectId'?

### ISSUE THREAD

**Issue by KeithGillette** [accounts-js/accounts#1248]
# Bug report

## Describe the bug
Running `tsc` from `typescript@4.9.5` with default `skipLibCheck: false` on a project importing ` @accounts/mongo@0.34.0` and `mongodb@5.1.0` generates the following error:
```
error TS2724: '"bson"' has no exported member named 'ObjectID'. Did you mean 'ObjectId'?
```

## To Reproduce
See bug description.

## Expected behavior
The project should transpile without error with TypeScript's default `skipLibCheck: false` setting.

## Screenshots
N/A

## System information
* accounts-js: 0.33.2
* mongodb: 5.1.0
* typescript: 4.9.5

## Additional context
The version of `mongodb` in `@accounts/mongo` dependencies is 2 major versions behind.

**Comment by darkbasic** [comment]
Please try [1.0](https://github.com/accounts-js/accounts/pull/1258), this should be fixed.
