### ISSUE TITLE
Package fails in NSP check

### ISSUE THREAD

**Issue by mdemri** [accounts-js/accounts#127]
────────┬────────────────────────────────────────────────────────────────────┐
│            │ Regular Expression Denial of Service                               │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Name       │ moment                                                             │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ CVSS       │ 7.5 (High)                                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Installed  │ 2.15.2                                                             │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Vulnerable │ <2.19.3                                                            │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Patched    │ >=2.19.3                                                           │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Path       │ XXXXXXXX > @accounts/server@0.0.18 >     │
│            │ emailjs@1.0.12 > moment@2.15.2                                     │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ More Info  │ https://nodesecurity.io/advisories/532                             │
└────────────┴────────────────────────────────────────────────────────────────────┘

**Comment by davidyaha** [comment]
Thanks @mdemri!
Our current codebase does not have dependency in momentjs so I guess that is not an issue on our latest releases.
Do you know what package is affected by it?

**Comment by mdemri** [comment]
@davidyaha you reference emailjs..

**Comment by mdemri** [comment]
@accounts/server@0.0.21 > emailjs@1.0.12 > moment@2.15.2

**Comment by davidyaha** [comment]
Ah gotcha! Thanks! Could you open the same issue on their github as well?

**Comment by pradel** [comment]
There is already an open issue on the package https://github.com/eleith/emailjs/issues/209

**Comment by pradel** [comment]
Fixed on the 0.1 version will write a changelog soon
