### ISSUE TITLE
Set organization avatar

### ISSUE THREAD

**Issue by TimMikeladze** [accounts-js/accounts#14]
Would be great to replace the generated organization avatar with something relevant.

**Comment by gadicc** [comment]
Some possible inspiration:

* [avatar-shield](https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn3.iconfinder.com%2Fdata%2Ficons%2Ftoolbar-people%2F512%2Fuser_shield_man_male_profile_account_person-512.png&imgrefurl=https%3A%2F%2Fwww.iconfinder.com%2Ficons%2F344973%2Faccount_authorization_avatar_client_contact_customer_human_man_manager_member_people_person_profile_protection_shield_user_users_icon&docid=jvmGFkE6Rj0O6M&tbnid=LbGpiWC0X3m69M%3A&w=512&h=512&safe=off&bih=888&biw=1503&ved=0ahUKEwjtkOuMsIbQAhVoq1QKHdP5CHwQMwizAShbMFs&iact=mrc&uact=8)
* [avatar-key](https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn2.iconfinder.com%2Fdata%2Ficons%2Fpicons-basic-1%2F57%2Fbasic1-111_user_security-512.png&imgrefurl=https%3A%2F%2Fwww.iconfinder.com%2Ficons%2F176151%2Faccess_authorization_authorize_lock_password_permissions_security_icon&docid=F0kFohY_hriDbM&tbnid=n9e1nlzRJBNTiM%3A&w=512&h=512&safe=off&bih=888&biw=1503&ved=0ahUKEwiIpZn_sIbQAhUoiFQKHXPNB5cQxiAIAygB&iact=c&ictx=1)
* [golden-key-man](https://www.google.com/imgres?imgurl=http%3A%2F%2Fpreviews.123rf.com%2Fimages%2Flumaxart2d%2Flumaxart2d0904%2Flumaxart2d090401501%2F4759212-Holding-The-Golden-Key-Stock-Photo-gold-man-key.jpg&imgrefurl=http%3A%2F%2Fwww.123rf.com%2Fphoto_4759212_holding-the-golden-key.html&docid=asimScEkN5M7NM&tbnid=Hu6z8dt-z8a4pM%3A&w=1300&h=1300&safe=off&bih=888&biw=1503&ved=0ahUKEwjmsdvgsYbQAhXkgVQKHRxdDXwQMwgtKA8wDw&iact=mrc&uact=8)
* [man-holding-key](https://www.google.com/imgres?imgurl=http%3A%2F%2Fthumb101.shutterstock.com%2Fdisplay_pic_with_logo%2F704791%2F390236107%2Fstock-photo-business-man-holding-big-key-390236107.jpg&imgrefurl=http%3A%2F%2Fwww.shutterstock.com%2Fcat.mhtml%3Fsafesearch%3D1%26search_type%3Dsimilar%26similar_photo_id%3D59992621%26sort_method%3Dpopular&docid=GGsSGO770Yo0AM&tbnid=1T3okhhl-2vfoM%3A&w=293&h=470&itg=1&safe=off&bih=888&biw=1503&ved=0ahUKEwjq6PqQtIbQAhUT2mMKHf68B00QMwgqKA4wDg&iact=mrc&uact=8)

**Comment by TimMikeladze** [comment]
@pradel Assigned to you since you're working with a designer on this. Do they have a github?

**Comment by pradel** [comment]
Can I close this one?

**Comment by davidyaha** [comment]
I think so!
