### ISSUE TITLE
stateless `resumeSession`?

### ISSUE THREAD

**Issue by amitport** [accounts-js/accounts#158]
If I understand correctly, in the current implementation *every* request queries the DB for the current session and user.

Kind of missing the point of using access token and refresh token IMO. 

Did you consider having the basic user info and role is stored in the access token and only validate against the db when using a refresh token ?

This will mean that access token cannot be revoked (they should be short lived ~15min), but also that the server can be truly stateless/session-less.

(also note that validating and extending refresh-tokens can be done by a different, less-stateless server)

**Comment by pradel** [comment]
Hey, you are right in the current behavior we do a request on each refresh token calls. We are refactoring some parts of the package for the next version and this will be fixed soon :)

**Comment by pradel** [comment]
@amitport the refresh flow is fixed published as v0.1.0-beta.3

**Comment by amitport** [comment]
@pradel  hmm that's also good, but actually, I was referring to the server implementation. Doesn't it currently always access the DB? even if the access token is valid? I think a big advantage of using JWT over cookies is that it enables services to be fully session-less (they just validate. that the caller is currently allowed to access the service and minimal metadata about the user is extracted from the token)

**Comment by pradel** [comment]
I understand that but the problem with that approach is you can't revoke a security token. So if someone get an accessToken he will be able to use the user account and you can't do anything for that.
Same, if someone succeed to stole the secret key you use to encrypt jwt, he will be able to impersonate every user on your system and you will not notice it.
I understand the stateless approach is more lightweight but it also comes with some security issues that can't be fixed.

But it would definitely be great to be able to choose between stateless and session!

For now as a default behavior we just want to be as secure as possible :)

**Comment by amitport** [comment]
I really think that stateless is a main point of using access+refresh tokens. I think otherwise, simple session based cookies+CSRF protection orobably make more sense.

In any case, you're right that permissions to be stale for a while, this is OK in many use cases (expiry of access token can be 15m and there will still be a great performance improvement). 

Regarding secret keys, you'll also have impersonation vulnerability with a DB check for every request...

**Comment by davidyaha** [comment]
Hey @amitport, absolutely correct for web based applications. Unfortunately (or not) most usages we know of needs to support both mobile and web applications.
For most mobile implementations, authorization token works best. Even if it retains only a session identifier.

Anyhow, we are going to allow you to choose your token storage: JWT/Cookies.
If you would like to join the effort, I know @Aetherall is working on it.
Also we are all available on slack! let me know if you would like to join!

**Comment by amitport** [comment]
Thanks @pradel

**Comment by pradel** [comment]
Cheers @amitport published as v0.28.0
