### ISSUE TITLE
Make 2fa a composite of two auth services 

### ISSUE THREAD

**Issue by davidyaha** [accounts-js/accounts#183]
Instead of relying on one 2fa mechanism that is closely bounded to password, we should try to come up with a way to create a `2FAuthService` class that will contain two auth services.
It will use the first's `AuthService.authenticate` method to get the user object and then call the second's `verify` method with the user object, in order for it to do it's thing and verify the user's identity.
If 2fa is enabled for that user, it will only create a session / auth token for that user after both methods have succeeded.
This flow is rather complicated to execute in our current architecture but will be possible at some point. 

Someone cares to chime in on the idea?

**Comment by Aetherall** [comment]
Maybe we should wait for the transport - auth relationship to be improved before trying to implement this kind of feature
We can stick to the actual implementation for 0.1.0, scince we just have password stable

**Comment by Aetherall** [comment]
So I guess we should first create a CodeAuthenticationService
which allow to authenticate with a code only,
then we can make the Two factor authentication service a composite of two AuthS

for this maybe we could put accounts-graphql aside for a moment, before we find a satisfying abstraction in the way to transport the informations....

maybe something like an utra dynamic route on `'/{path}'` which takes params like this :

```ts
const requestParams = {
	password: {
		verifyEmail : { token: '', address: ''}
	}
}
```

so we can do 
```ts
const requestParams = {
	twoFactor: {
		authenticate : {
			password: { email: '', password: '' },
			code: { code: '' }
		}
	}
}
```

I do believe that routes like 
`'/${path}/password/verifyEmail'` and a little less but still `'/${path}/:service/:?provider/:action'`
 are a limitation

**Comment by pradel** [comment]
I am closing this issue as the MFA pr is currently in progress :) https://github.com/accounts-js/accounts/pull/813
