### ISSUE TITLE
Feature: Masquerade as another user

### ISSUE THREAD

**Issue by gadicc** [accounts-js/accounts#2]
Useful for checking a non-admin's user experience.  Should:
- [ ] Be disabled by default
- [ ] Require an explicit user-provided access check function to enable
- [ ] Possibly not rely on JWT and do an explicit access check at request time
- [ ] Keep track of original user on the client, with UI hint to switch back
- [ ] Keep track of original user in context, for logging purposes

**Comment by TimMikeladze** [comment]
Great idea, I'd love to see this supported in the future.

**Comment by gadicc** [comment]
There's a lot of exciting stuff we can do with accounts as it's own project vs a small part of another.  I might jot down a few ideas here and there that I'll milestone as "longer term" - don't feel obligated to acknowledge each one but yeah I hope you'll find the ideas as exciting as I do :)

**Comment by TimMikeladze** [comment]
Relevant discussions https://github.com/apollostack/meteor-integration/issues/44

**Comment by davidyaha** [comment]
closed a long time ago
