### ISSUE TITLE
AccountsLink for Apollo Link and userLoader in graphql context

### ISSUE THREAD

**Issue by Aetherall** [accounts-js/accounts#209]
In the future, We will need a fancy way to have the authenticated user in the resolvers of graphql API's

**Comment by pradel** [comment]
It's really easy to do it with `userLoader`, we only need to document it.

**Comment by Aetherall** [comment]
And what about having an apollo link on client side ? 
We could handle any requests as a middleware and inject tokens depending on the ClientTokenStorage configured

**Comment by kamilkisiela** [comment]
If you guys need some help with Apollo related work, feel free to message or @mention me, I could help

**Comment by pradel** [comment]
I don't know if a separate package is really needed right now because lot of stuff will change soon, maybe we can create a cookbook page for Apollo integration the docs?

**Comment by pradel** [comment]
We now have a @accounts/apollo-link package!
