### ISSUE TITLE
how does the email (verify, enroll, resetassword) work???

### ISSUE THREAD

**Issue by shaunzeng** [accounts-js/accounts#218]
How does the email work ? I am able to config and build the project with no issue, I just wonder how to trigger those email to be sent? when I create a new user , no email is sent to verify my email address? Sorry I do appreciate all the work, but there is no much about the email in the documentation.

**Comment by pradel** [comment]
Hey thanks for your interest in the module, right now when you instantiate a new project the emails will be printed to the console.
If you want to send emails with your email provider you have to provide a `sendEmail` option with the following signature: `(mail: object) => Promise<void>;`
Example:
```
const server = new AccountsServer({
  sendEmail: (mail) => {
    // use mailgun api here to send a real email for example
  }
})
```

**Comment by Ethaan** [comment]
@pradel i see you guys use https://github.com/eleith/emailjs, but how can i config the `AccountsServer` to use my gmail account for example?

```
	const accountsServer = new AccountsServer({
		db: accountsDb,
		mail: { // this?
			ssl: true,
			user: 'hello@hello.com',
			host: 'smtp.googlemail.com',
			port: 465,
			password: 'password',
		},
		tokenSecret: TOKEN_SECRET,
	}, {
		password: accountsPassword
	});
```
i get `No configuration for email, you must set an email configuration`

**Comment by pradel** [comment]
@Ethaan we were using emailjs before but we removed this dependency so you can use any email lib you want.
I think it would be great to have some examples in our documentation.
If you are using nodemailer you can do something like that:
```js
// initialise nodemailer gmail transporter before

	const accountsServer = new AccountsServer({
		db: accountsDb,
		sendMail: async (mail) => {
           await transporter.sendMail({
             from: mail.from,
             to: mail.to,
             subject: mail.subject,
             text: mail.text,
             html: mail.html
          });
        },
		tokenSecret: TOKEN_SECRET,
	}, {
		password: accountsPassword
	});
```

**Comment by pradel** [comment]
@Ethaan I created a quick pr for the email documentation if you want to take a look https://github.com/accounts-js/accounts/blob/2b4e721662c9702b95002b00bacb9477203433e4/docs/email.md
