### ISSUE TITLE
Feature: User's session and service management

### ISSUE THREAD

**Issue by gadicc** [accounts-js/accounts#3]
A user should be able to:
- [ ] See their logged in devices and revoke specific tokens
- [ ] See linked services and disassociate them individually
- [ ] Link new services where email doesn't match (otherwise should be auto on login)

**Comment by davidyaha** [comment]
Not really sure if this approach fit's our current roadmap anymore. 
Will be interesting to re-visit when offering some "access directory" like features. Probably as a different product from this org.
Closing for now.

**Comment by pradel** [comment]
I think with the current implementation users will be able to implement that pretty easily
