### ISSUE TITLE
Option to obfuscate user infos

### ISSUE THREAD

**Issue by pradel** [accounts-js/accounts#337]
Would be great to have an option to obfuscate the user infos. So for example instead of 'user not found' we need to say 'Invalid credentials' on the login error messages (and others)

**Comment by pradel** [comment]
Meteor is using the `ambiguousErrorMessages` option, see https://docs.meteor.com/api/accounts-multi.html#AccountsCommon-config

**Comment by pradel** [comment]
@Aetherall what was your idea with the error class for this one already?

**Comment by Aetherall** [comment]
My first idea was : 

The `@accounts/error` package should contain a file exporting the instance of an AccountsMessage class

the instance is used by the AccountsError class to assign the message to the error code

we can register a translation set to the AccountsMessage class

____

but I think we should be able to set the language depending on the request

So maybe we should not use AccountsMessage in the AccountsError class directly but use it in the transport, where we can use an user defined function "getLocaleFromRequest" to apply the correct translation to the correct user

So, the error occurs, the error is created, it bubbles up to the transport, the error is humanreadablised, and then sent to the user
