### ISSUE TITLE
How to turn on debug messages?

### ISSUE THREAD

**Issue by rankun203** [accounts-js/accounts#349]
I'm having issue creating a user, then I realized I can't find a way to turn on debug messages. How do you debug with accounts-js?

For people who care, my accounts-js.ts script:

```javascript
import { AccountsServer } from '@accounts/server';
import { AccountsServerOptions } from '@accounts/server/lib/types/accounts-server-options';
import { AuthenticationService } from '@accounts/types';
import { DatabaseManager } from '@accounts/database-manager';
import { createJSAccountsGraphQL } from '@accounts/graphql-api';
import { AccountsPassword } from '@accounts/password';
import { RedisSessions } from '@accounts/redis';
import MongoDBInterface from '@accounts/mongo';

import redis from './db-redis';
import { createMongoConn } from './db-mongo';

const { ACCOUNTS_TOKEN_SECRET, MONGO_URL_ACCOUNTS } = process.env;

if (!ACCOUNTS_TOKEN_SECRET) {
  throw 'accounts-js.ts missing env ACCOUNTS_TOKEN_SECRET';
}
if (!MONGO_URL_ACCOUNTS) {
  throw 'accounts-js.ts missing env MONGO_URL_ACCOUNTS';
}

// Create MongoDB Connection
const mongoConn = createMongoConn(MONGO_URL_ACCOUNTS);

// TODO: documentation required.
const sessionStorage = new RedisSessions(redis);
const userStorage = new MongoDBInterface(mongoConn);

const accountsDb = new DatabaseManager({ sessionStorage, userStorage });

const accountsServerOptions: AccountsServerOptions = {
  db: accountsDb,
  tokenSecret: ACCOUNTS_TOKEN_SECRET
};
const accountsServices: { [key: string]: AuthenticationService } = {
  password: new AccountsPassword()
};

const accounts = new AccountsServer(accountsServerOptions, accountsServices);

const accountsGraphql = createJSAccountsGraphQL(accounts);

export const schema = accountsGraphql.schema;
export const extendWithResolvers = accountsGraphql.extendWithResolvers;
```

Sorry for submitting another _how to_ issue.

Thanks

**Comment by pradel** [comment]
Hey @rankun203 for now we don't have a debug strategy like the one you are asking for.
However I don't think the graphql api package is compatible with the 0.1 version unfortunately.

**Comment by pradel** [comment]
We still need to migrate it to the monorepo and make it work with the latest release.

**Comment by rankun203** [comment]
@pradel Do you suggest me to dig deeper and try to make it work? I have limited time to set this thing up but I'm curious about your plan of when GraphQL will work, if it works for me I'll stay with accounts-js.

**Comment by pradel** [comment]
For now I would suggest you to use the express rest api which is working well since we don't know when we will have time to finish the work on the graphql package. When the graphql package will be ready migrating from one to another will be pretty easy.
Or if you want to migrate the graphql package to make it work with 0.1 pull requests are always welcome :)

**Comment by rankun203** [comment]
@pradel Do you consider using [debug](https://www.npmjs.com/package/debug) as a debug messaging tool?

Actually not just this repo, some other repos I visited (for example the one provides graphql server tool) also do not have debug messaging enabled by default. Am I missing something here? How do people work with debug logs? Or it's just early stage people don't use it, then once a stable release published they will starting to use it?

I'm happy to see if there is any new ways to debug my app.

**Comment by rankun203** [comment]
Since the answer is clear, closing issue.

**Comment by pradel** [comment]
Thank you @rankun203 🙏 will have a look soon!
