### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by elie222** [accounts-js/accounts#354]
I know this was an option before the big refactor. Does this still work? Are the AccountsJS packages in the process of being moved over to the new monorepo?

**Comment by elie222** [comment]
Took a deeper look at things. I see the examples use RestClient from this project. 
Would using GraphQL client from here work just as well?
https://github.com/accounts-js/graphql

**Comment by pradel** [comment]
Hey, currently the graphql package is not compatible with the latest version.
But we just get a pr today that will add the support soon thanks to @rankun203 you can track the progress here https://github.com/accounts-js/graphql/pull/28.
