### ISSUE TITLE
Move common type definitions to packages/types

### ISSUE THREAD

**Issue by rankun203** [accounts-js/accounts#355]
Currently if I want to reference PasswordCreateUserType from `@accounts/password`, I need to import like this:

```ts
import { PasswordCreateUserType } from '@accounts/password/lib/types';
```

See [register-user.ts#L4](https://github.com/rankun203/graphql/blob/kun/latest-server-compatible/packages/graphql-api/src/resolvers/register-user.ts#L4)

Which makes tslint complains about:

> Submodule import paths from this package are disallowed; import from the root instead (no-submodule-imports)

Maybe we can either do:

1. move all those types into packages/types
2. export those types from `@accounts/password` so I can reference it outside of its package.

**Comment by pradel** [comment]
I think option 2 should be fine :)

**Comment by rankun203** [comment]
PR submitted accounts-js/accounts#358.
