### ISSUE TITLE
Improving the graphql package

### ISSUE THREAD

**Issue by pradel** [accounts-js/accounts#362]
I was thinking about how to improve the graphql package.
- [x] export a `@authenticated` which will have the same behavior as the current `authenticated` function.
- [x] export the resolver object and let the user merge the resolvers himself (with lodash merge for example) instead of `accountsGraphQL.extendWithResolvers`.
- [x] remove the profile key on the CreateUserInput type
- [x] remove the email key on the User type.

Do you have other other ideas?

**Comment by Aetherall** [comment]
> export a @authenticated directive to replace the current authenticated function.
Maybe we should add it instead of replacing it, the authenticated function could be usefull for resolvers where authentication is needed depending on the parameters or the object

>  export the resolver object and let the user merge the resolvers himself instead
I agree :+1:

**Comment by pradel** [comment]
Maybe we can also remove the `email` key on the `User` type. Right now internally we use an array of emails so it make no sense to get that email key which is a string.

**Comment by pradel** [comment]
By default I think we should remove the profile key on the `CreateUserInput` type. We can add docs to let the user know how to extend the type with a profile

**Comment by Aetherall** [comment]
I agree for both of those points :+1:

**Comment by TimMikeladze** [comment]
Started work on the remaining two tasks here https://github.com/accounts-js/accounts/pull/366
