### ISSUE TITLE
Throw error if accounts server was created with no services

### ISSUE THREAD

**Issue by elie222** [accounts-js/accounts#372]
I created AccountsServer with an empty services object. Then when I went to register with:

```gql
mutation register {
  register(user: {email: "hello@example.com", password: "password"})
}
```

It threw an error on this line:
https://github.com/accounts-js/accounts/blob/master/packages/graphql-api/src/resolvers/register-user.ts#L10

I take it a user always has to register at least one service? If so, we should throw an error when a user creates a server with an empty services object?

Beyond that, I take it from the code above, you must be using the password service when using graphql.

**Comment by pradel** [comment]
Maybe just initialise the service private object as an empty object?

**Comment by elie222** [comment]
I did that first. But then it threw an error because it didn't have a password service.

**Comment by pradel** [comment]
Okay I think in that case we should only expose the resolvers + types associated with the current `AccountsServer` instance

**Comment by elie222** [comment]
Does it ever make sense to create an `AccountsServer` instance with 0 services?

**Comment by TimMikeladze** [comment]
I'm not sure AccountsServer can work with 0 services, there's no practical scenario for it, but an empty object may be required for some AccountsServer test cases?

When creating the accounts schema, we need to detect 
https://github.com/accounts-js/accounts/blob/master/packages/graphql-api/src/schema-builder.ts#L78 what options were provided to accounts server and only build the corresponding schema.

**Comment by elie222** [comment]
If an empty service object is required for tests I would say we just update
the tests and use a mock service if needed.
