### ISSUE TITLE
Question/suggestion: Default mongo date provider

### ISSUE THREAD

**Issue by elie222** [accounts-js/accounts#376]
Why is this the default mongo date provider:

https://github.com/accounts-js/accounts/blob/babf3bb6f41673cb99e85be0f08daaeae295d0a8/packages/database-mongo/src/mongo.ts#L29

Rather than:

```js
dateProvider: (date?: Date) => (date ? date : new Date()),
```

As this is what [mongoose timestamps](http://mongoosejs.com/docs/guide.html#timestamps) does.

**Comment by pradel** [comment]
If I remember correctly it was done like this because it was easier to mock during the tests. If you want the same behavior as mongoose you can provide the `dateProvider` option to mongo
