### ISSUE TITLE
Register flow

### ISSUE THREAD

**Issue by elie222** [accounts-js/accounts#377]
After registering through GraphQL a user isn't automatically logged in. He just gets back his user id:

```gql
register(user: CreateUserInput!): ID
```
https://github.com/accounts-js/accounts/blob/master/packages/graphql-api/src/graphql/mutations.ts#L11

After which he needs to log in:

```gql
authenticate(serviceName: String!, params: AuthenticateParamsInput!): LoginResult
```
https://github.com/accounts-js/accounts/blob/master/packages/graphql-api/src/graphql/mutations.ts#L8

The client can handle both steps for the user automatically, but is this the intended flow rather than just logging the user in automatically upon register?

**Comment by TimMikeladze** [comment]
I think automatic login on registration is something we could expose in the options, and possibly even enable it by default.

A scenario where a user doesn't need to be logged in automatically on signup is if they need to await for an email to confirm their account (I don't know if we support that feature, but if we don't we will in the future).

**Comment by lorensr** [comment]
Seems like it would be a nice default. It's the behavior of [`Accounts.createUser` in Meteor](https://docs.meteor.com/api/passwords.html#Accounts-createUser)

**Comment by elie222** [comment]
I agree it's a nice default.

Would it make sense for me to add registerAndAuthenticate endpoint (that
would cover that flow and do both items in one step)?

The alternative is to just update register to do that itself.

Elie

**Comment by pradel** [comment]
What do you think about adding an option to the password package something like `authenticateAfterCreateUser` which will default to true. Then the createUser function will either return a string which is the user id if the option is false or the `LoginResult` if the option is true. The graphql signature will look like this `register(user: CreateUserInput!): ID | LoginResult`.

**Comment by elie222** [comment]
Starting to work on this issue now.

**Comment by elie222** [comment]
Ok. I see it's a bit of work. Leaving this for another time.

To register and log in a user you can do the following however which is simple enough. Should just be documented for people:

```js
      const email = 'hello@email.com'
      const password = 'PASSWORD'

      await accountsPassword.createUser({
        email,
        password,
      })

      await accountsPassword.login({
        password,
        user: {
          email,
        },
      })
```

**Comment by sakulstra** [comment]
I just looked into the source but didn't get why `createUser` returns `null` when there's *no* `ambiguousErrorMessages` and `userId` if there is. Couldn't we just change:
```
// schema
- createUser(user: CreateUserInput!): ID
+ createUser(user: CreateUserInput!): LoginResult

// mutation
-  createUser: async (_, { user }, { injector }) => {
+  createUser: async (_, { user }, ctx) => {
+    const { ip, userAgent, injector } = ctx;
     const userId = await injector.get(AccountsPassword).createUser(user as PasswordCreateUserType);
-    return injector.get(AccountsServer).options.ambiguousErrorMessages ? null : userId;
+    const authenticated = await injector.get(AccountsServer).loginWithService("password", user, {
+      ip,
+      userAgent,
+    });
+    return injector.get(AccountsServer).options.ambiguousErrorMessages ? authenticated : userId;
```

For people not using the accounts-js/client implementation this should be enough to get things done :thinking:

**Comment by pradel** [comment]
This option has been added in the latest release :) https://github.com/accounts-js/accounts/releases/tag/v0.25.0
