### ISSUE TITLE
accounts-password compatibility

### ISSUE THREAD

**Issue by lorensr** [accounts-js/accounts#385]
I have a Mongo users collection created by Meteor's `accounts-password`. I want it to work with a non-Meteor express server. Can I add `@accounts/password` to my express server and have it understand my user doc format? If not, can I do a db migration and put the `services.password.bcrypt` value where `@accounts/password` expects, or does `@accounts/password` not use bcrypt?

![image](https://user-images.githubusercontent.com/251288/42719390-c0e14a6a-86e2-11e8-8f8a-db3bfa988574.png)

(test user in dev db 😄)

**Comment by lorensr** [comment]
Thanks, looks like I need these Mongo options:

```js
import randomString from 'crypto-random-string'

const METEOR_ID_LENGTH = 17
const idProvider = () => randomString(METEOR_ID_LENGTH)

new MongoDBInterface(mongoConn, {
  convertUserIdToMongoObjectId: false,
  idProvider
});
```

but then I'm getting this:

![image](https://user-images.githubusercontent.com/251288/42742664-8f1eed76-888a-11e8-8bca-cbc7da2646fa.png)

So I'm guessing there's a difference between Meteor and accounts-js default hashing strategies?Maybe I just need the right option for `passwordHashAlgorithm`? https://github.com/accounts-js/accounts/blob/master/packages/password/src/accounts-password.ts#L26

cc @davidyaha

**Comment by pradel** [comment]
Looks like meteor is using SHA256 before bcrypt on the server side https://github.com/meteor/meteor/blob/52532e70e53631657d55aa60409bca6f3e243922/packages/accounts-password/password_server.js#L45, we use this only on the client side, not on the server side, you should try to use the option and set `sha256` as a value.

**Comment by lorensr** [comment]
Thanks, that works! Working on a package aimed at replacing accounts-password, will add it to docs here when it's ready.
