### ISSUE TITLE
React Native Support?

### ISSUE THREAD

**Issue by rankun203** [accounts-js/accounts#391]
We are currently using this as a universal solution for accounts, but having trouble making it work with React Native, since it does not have a standard browser environment.

Is there any plan to support React Native?

**Comment by pradel** [comment]
Hey, which error are you facing? Since we are using only browser compatible modules for the client it should work. I tried with react-native a few month ago and it was working well.

**Comment by rankun203** [comment]
@pradel It does not send credentials like it does in the browsers. There are chances that I'm doing it wrong, I will do some more investigations later.

**Comment by rankun203** [comment]
Verified that accounts-js do works with RN, I had to set the auth headers for my own requests, but accounts-js already provided `refreshSession()` function, I only need to detect duplicate `refreshSession()` requests.

**Comment by rankun203** [comment]
@lorensr We know we had to initialize everything at app launches, but actually our Apollo Client is dependent on Accounts Client (to automatically append auth `accounts-access-token` onto HttpLink), also Accounts Client is dependent on Apollo Client (to transport data).

We have a singleton, which has constructor like this:

```ts
  constructor() {
    if (!LSApolloClient.options) {
      throw new Error('options does not exist');
    }

    const {
      credentials,
      headers,
      fetchOptions,
      serverURL
    } = LSApolloClient.options;
    if (!(serverURL && serverURL.length > 0)) {
      throw new Error('Server URL cannot be empty');
    }

    this.client = new ApolloClient({
      link: ApolloLink.from([
        lsErrorLink,
        new HttpLink({
          uri: serverURL,
          fetchOptions: fetchOptions || {},
          // credentials: 'included'
          credentials: credentials || 'same-origin',
          headers: headers || {},
          fetch: genFetcher({
            'accounts-access-token': this.getAccessToken.bind(this)
          })
        })
      ]),
      cache: new InMemoryCache()
    });

    return this;
  }
```

Only then we can decide the initialization flow.

Another issue you will be facing is the implementation of `getAccessToken()` on the ApolloClient side (cross dependency). We have a method like this:

```ts
  public async getAccessToken(uri: string, options: RequestInit) {
    if (!this.accountsClient) {
      return null;
    }

    // ! Important, if current request is refreshTokens request, DO NOT refresh again!
    const tokens =
      options.body &&
      typeof options.body === 'string' &&
      options.body.includes('refreshTokens')
        ? await this.accountsClient.getTokens()
        : await this.accountsClient.refreshSession();

    return tokens && tokens.accessToken;
  }
```

Above solutions may not be the best way to do this, if anyone have any better idea, please leave comments below :)
