### ISSUE TITLE
Add additional fields to user model

### ISSUE THREAD

**Issue by rankun203** [accounts-js/accounts#394]
What is the suggested way to add additional fields to user?

**Comment by rankun203** [comment]
Currently I'm creating a local `UserMeta` just for storing user properties like roles, but still, I'm looking for a better way to do this job.

**Comment by pradel** [comment]
Currently we are providing a profile key to let to the user the ability to add more fields.
I am not super happy with the current solution which is quite limiting.
In my opinion we should remove the profile key and save the whole user object in the database. In that way the user can still continue to use the profile key if he wants to or use the `user` root fields. The user will be able to provide a function to validate the user and only allow some fields for example.

**Comment by pradel** [comment]
Let's use this issue to discuss about this feature :)

**Comment by TimMikeladze** [comment]
Your solution sounds good to me @pradel

**Comment by pradel** [comment]
See https://github.com/accounts-js/accounts/pull/438 which should solve this problem
