### ISSUE TITLE
resetPassword broken?

### ISSUE THREAD

**Issue by lorensr** [accounts-js/accounts#396]
Using the graphql example, when I trigger the reset password mutation, the response is `null`, and afterward, I can't login with either the old nor the new password.

**Comment by pradel** [comment]
hum yeah looks like the example is not working, you need to replace on this line https://github.com/accounts-js/examples/blob/master/react-graphql-typescript/src/ResetPassword.tsx#L69 `accountsGraphQL.resetPassword` with `accountsPassword.resetPassword` (and of course import it) and it will work :)

**Comment by lorensr** [comment]
That fixes it, thanks!

**Comment by pradel** [comment]
Fixed see https://github.com/accounts-js/examples/pull/183
