### ISSUE TITLE
Emails and password reset

### ISSUE THREAD

**Issue by TimMikeladze** [accounts-js/accounts#40]
The following should be implemented, additional details can be found here http://docs.meteor.com/api/passwords.html. 

An important detail to note in the email implementation is that should be generic enough for consumers to plugin their own email service. For example using the mailgun api vs using their own smtp server.

**Server**
- [x] addEmail
- [x] removeEmail
- [x] sendResetPasswordEmail
- [ ] sendEnrollmentEmail
- [x] sendVerificationEmail
- [x] resetPassword
- [ ] sendWelcomeEmail

**Server config**
- [ ] sendVerificationEmail (default false)
- [ ] sendEnrollmentEmail (default false)
- [ ] sendWelcomeEmail (default false)
- [ ] email template for each email type, consider using https://github.com/mjmlio/mjml

**Client**
- [ ] requestPasswordReset
- [ ] requestVerificationEmail

**Client config**
- [ ] onResetPasswordLink
- [ ] onEnrollmentLink
- [ ] onEmailVerificationLink

**Comment by pradel** [comment]
For the mail implementation I found this lib https://github.com/eleith/emailjs who looks good. I was using [nodemailer](https://github.com/nodemailer/nodemailer) but they changed their licence since v3

**Comment by pradel** [comment]
Btw I am not sure we should provide email templates.
I think we could have only text emails and let the user do his own template.

**Comment by TimMikeladze** [comment]
Sounds good to me.
