### ISSUE TITLE
add usesTwoFactor

### ISSUE THREAD

**Issue by lorensr** [accounts-js/accounts#407]
Two use cases:
- login form: user types in email/username, we do `query { usesTwoFactor(username: "foo") }` to determine whether to show the 2fa input
- demo home /: `query { getUser(accessToken: "bar") { usesTwoFactor } }` so we know whether to show the "set up 2fa" link.

```js
Query: {
  usesTwoFactor: (root, args) => {
    const user = Users.findOne({username: args.username}) // or email
    return Boolean(get(user, 'services.two-factor'))
  }
}
User: {
  usesTwoFactor: (user) => {
    return Boolean(get(user, 'services.two-factor'))
  }
}
```

**Comment by pradel** [comment]
It's a good idea ta add a field to the user object.
I don't think we should add this `usesTwoFactor` query, we should rethink the way about two factor is currently done. I will write a RFC for this part soon but it will be in two step so you will be able to show the 2fa input or not.

**Comment by pradel** [comment]
I am closing this issue as the MFA pr is currently in progress :) https://github.com/accounts-js/accounts/pull/813
