### ISSUE TITLE
Automatically adding user to graphql resolver context

### ISSUE THREAD

**Issue by elie222** [accounts-js/accounts#421]
I see the code has `authenticated` as shown here:

```
changePassword: authenticated(accountsServer, changePassword(accountsServer)),
```

Would it make sense to just add authenticated to the context and have the `user` object available for every request made to the server?

Right now I have this in my code:

```ts
const server = new ApolloServer({
  typeDefs: [typeDefs as any, accountsGraphQL.typeDefs],
  resolvers: merge(accountsGraphQL.resolvers, resolvers),
  context: async ({ req }) => {
    const ctx = accountsContext(req)
    const { authToken } = ctx

    let user

    try {
      user = await accountsServer.resumeSession(authToken as string)
    } catch (error) {}

    return {
      ...ctx,
      user,
      userId: user && user._id,
    }
  },
})
```

Seems something like this would be useful for all users of the `graphql-api` package. Would it make sense to have `accountsContext` also return the user object if it exists.

**Comment by TimMikeladze** [comment]
This sounds like a good improvement to me.

**Comment by elie222** [comment]
Is resume session as in the code above the best way to do this?

**Comment by TimMikeladze** [comment]
I think so. After this change do you think the `getUser` query is still needed? Or perhaps it could be modified to return `context.user` if it exists?

**Comment by elie222** [comment]
I'm not sure I follow why it wouldn't be needed.

If the client wants to get information about the current user, getuser
would still be the way to do it, no?

**Comment by TimMikeladze** [comment]
Yeah sorry I worded that incorrectly. I meant to say that it should be modified to use `context.user` if it exists instead of doing `Accounts.resumeSession`.

**Comment by pradel** [comment]
@elie222 was wondering does throwing inside the context function create a formatted graphql error?

**Comment by lorensr** [comment]
AFAICT, the current behavior is that whenever there's a valid access token stored on the client, it's included in a header, and `accountsContext()` provides a `context.user` object to all of my resolvers.

**Comment by elie222** [comment]
Are you sure about that? Will need to check again. I had to add that
functionality myself because I didn't see it already included. I just the
ip and access token sent on with no user object.

**Comment by pradel** [comment]
I just submitted a pull request for that https://github.com/accounts-js/accounts/pull/437
