### ISSUE TITLE
GraphQL errors sending stack traces

### ISSUE THREAD

**Issue by elie222** [accounts-js/accounts#424]
Not sure if this is a development vs production thing, but the server is sending a lot more information than it should to the client in development.

The stack trace shows the full trace when expanded.

<img width="509" alt="screen shot 2018-08-01 at 10 44 40" src="https://user-images.githubusercontent.com/3090527/43508211-f5b56dea-9577-11e8-9534-1ee44aa31eed.png">

The query used was:

```gql
  getUser {
    emails {
      address
      verified
    }
  }
```

**Comment by pradel** [comment]
yeah it's the behavior of apollo server if you set NODE_ENV to production the stacktrace will not be sent to the client
