### ISSUE TITLE
Add error dictionary

### ISSUE THREAD

**Issue by davidyaha** [accounts-js/accounts#43]
Define a map that has an error code mapped to an object that holds `technicalMessage` and `humanizedMessage` to be used on view layer packages.

**Comment by TimMikeladze** [comment]
Thoughts on supporting internalization? I think all that's necessary on our part is to allow an optional error dictionary to be passed in.

**Comment by davidyaha** [comment]
Mmmm true. Merge in with our dictionary.

**Comment by davidyaha** [comment]
not relevant at this point.
