### ISSUE TITLE
Deprecation warning in Mongo package for url parser

### ISSUE THREAD

**Issue by TimMikeladze** [accounts-js/accounts#436]
> (node:96837) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.

**Comment by pradel** [comment]
It's an option issue, if you want to get rid of the warning you have to pass the `useNewUrlParser` option when you call connect:
```
const config = {
  useNewUrlParser: true,
};
return mongoose.connect(uri, {config});
```

**Comment by pradel** [comment]
I don't think it's related to accounts-js no?

**Comment by TimMikeladze** [comment]
Ah got it. Thanks closing.
