### ISSUE TITLE
[HELP] How to use accounts server with apollo-server-micro?

### ISSUE THREAD

**Issue by williamli** [accounts-js/accounts#467]
I would like to know if it is possible to swap out the following express middleware (from docs) with something that works in `micro`.

I am using this [Fully Custom Routing Example](https://www.npmjs.com/package/apollo-server-micro#fully-custom-routing-example) on micro with apollo server.

```
import { accountsContext } from '@accounts/graphql-api';

app.use(
  GRAPHQL_ROUTE,
  bodyParser.json(),
  graphqlExpress(request => {
    return {
      context: {
        ...accountsContext(request),
        // your context
      },
      schema,
    };
  })
);
```

**Comment by pradel** [comment]
Since we are using the graphql context we are not linked to any special middleware, it should work with express, micro etc..

**Comment by TimMikeladze** [comment]
@williamli Take a look at the README or the accounts boost examples to see how to use the 
context function.

Feel free to reopen this issue if you have questions or contact us on Slack.
