### ISSUE TITLE
[HELP] How to create AccountsClient to generate the authLink required in GraphQL?

### ISSUE THREAD

**Issue by williamli** [accounts-js/accounts#470]
In 
https://accounts-js.netlify.com/docs/transport/graphql/#hook-it-up-to-the-apollo-client

```
import { accountsLink } from '@accounts/apollo-link';

const accountsClient = new AccountsClient( ... );
const authLink = accountsLink(accountsClient);

export const apolloClient = new ApolloClient({
  link: ApolloLink.from([authLink, httpLink]),
  cache,
});
```

What is an AccountsClient?

Is it `import { AccountsClient } from '@accounts/client';` ?
If so, what is the _accountsTransport_ required to construct AccountsClient?

**Comment by williamli** [comment]
If I need a _apolloClient_ to get a _ accountsGraphQL_

```
const apolloClient = new ApolloClient({
  // apollo options
});

const accountsGraphQL = new AccountsGraphQLClient({
  graphQLClient: apolloClient,
  // other options
});
```

but then I need a _ accountsGraphQL_ in order to generate the _ authLink_ to create the _ apolloClient_ ?

```
import { accountsLink } from '@accounts/apollo-link';

const accountsClient = new AccountsClient( ... );
const authLink = accountsLink(accountsClient);

export const apolloClient = new ApolloClient({
  link: ApolloLink.from([authLink, httpLink]),
  cache,
});
```

**Comment by williamli** [comment]
or do I need 2 layers of ApolloClient?

```
const apolloClient1 = new ApolloClient({ uri: 'https://nx9zvp49q7.lp.gql.zone/graphql' });

const accountsGraphQL = new AccountsGraphQLClient({
  graphQLClient: apolloClient1,
  // other options
});

const authLink = accountsLink(accountsGraphQL);


export const apolloClient2 = new ApolloClient({
  link: ApolloLink.from([authLink, httpLink]),
  cache,
});

```

**Comment by williamli** [comment]
I just tried the 2 layers ApolloClient approach mentioned above and it doesn't work.

It also breaks the ApolloClient and I can no longer query anything.

**Comment by williamli** [comment]
@TimMikeladze @pradel is it possible for us to have a 30 to 60 minutes video call to go through my current (mostly boilerplate) code in exchange for a 2 years contribution to https://opencollective.com/accounts-js ?

I am working on a client project that consists of react (in Next) + micro js backend integrated with graphQL (Apollo).

Right now GraphQL without authorization works perfectly and I need a **quick** kickstart with integrating accounts.js into the microservices.

I got part of the GraphQL client setup but is stuck due to the lack of documentation and since I just started GraphQL, there are still a lot of guessworks in going through all the code...


thanks.

**Comment by TrillCyborg** [comment]
I'm having the same problem. It's difficult to understand how to do this properly

**Comment by TrillCyborg** [comment]
@williamli I got this working with this code snippet written by @elie222. You need to use 2 graphql clients

`
import { ApolloClient } from 'apollo-client'
import { ApolloLink } from 'apollo-link'
import { createHttpLink } from 'apollo-link-http'
import { InMemoryCache } from 'apollo-cache-inmemory'
import { AccountsClient } from "@accounts/client";
import { AccountsClientPassword } from "@accounts/client-password";
import GraphQLClient from "@accounts/graphql-client";
import { accountsLink } from '@accounts/apollo-link'

const uri = /* gql endpoint */

const cache = new InMemoryCache()
const httpLink = createHttpLink({
  uri,
})

export const graphQLApolloClient = new ApolloClient({
  link: ApolloLink.from([httpLink]),
  cache,
})

export const accountsGraphQL = new GraphQLClient({
  graphQLClient: graphQLApolloClient
});
export const accountsClient = new AccountsClient({}, accountsGraphQL);
export const accountsPassword = new AccountsClientPassword(accountsClient);
const authLink = accountsLink(accountsClient)

const apolloClient = new ApolloClient({
  link: ApolloLink.from([authLink, httpLink]),
  cache,
});

export default apolloClient;
`

**Comment by pradel** [comment]
Hey, until we find a better solution, you can use 2 apollo client for now yes!

**Comment by pradel** [comment]
@williamli we are all available on slack, let me know if you would like to join :)

**Comment by williamli** [comment]
sure. please add williamli [at] bbi.io <http://bbi.io/>

**Comment by pradel** [comment]
@williamli invitation sent

**Comment by yellowspaceboots** [comment]
Has a better solution be created for this? I looks like according to the docs that you still need 2 apollo clients but I cannot get it to work.

**Comment by elie222** [comment]
See this example:
https://github.com/elie222/bike-sharing/blob/master/client/src/utils/apollo.ts

**Comment by pradel** [comment]
If someone wants to submit a pr to update the docs 🙏

**Comment by Akarshit** [comment]
I feel this issue should still be open, it is really hard to figure out how to do this from the docs.
