### ISSUE TITLE
Deactivate user

### ISSUE THREAD

**Issue by TimMikeladze** [accounts-js/accounts#48]

**Comment by davidyaha** [comment]
I think accounts.js should never be able to remove a user. Lets settle for a deactivate?
What do you think @TimMikeladze

**Comment by pradel** [comment]
What should be the name of the field? `blocked`, `deactivated`, other ...?

Steps to do:
- create the `deactivateUser` and `activateUser` functions for the database adapters.
- Add the field to the user object as false when we create the user.
- create a `deactivateUser` | `blockUser` function on `accounts/server`.
- create a `activateUser` | `unBlockUser` function on `accounts/server`.
- check during the authentication process if the `blocked` | `deactivated` field on the user object is not true.

**Comment by lorensr** [comment]
`deactivateUser/activateUser` and a user field: `deactivated: true`. (absense of field means user is active)

**Comment by pradel** [comment]
Pull request ready for this issue see https://github.com/accounts-js/accounts/pull/480

**Comment by acomito** [comment]
Just used this feature! thanks
