### ISSUE TITLE
[graphql-api] `withSchemaDefinition` option is not working

### ISSUE THREAD

**Issue by pradel** [accounts-js/accounts#499]
With the latest release of accounts-js (0.6) when get the typedefs using the `withSchemaDefinition` option set to false the schema definitions are still included see:
```js
const accountsGraphQL = AccountsModule.forRoot({
  accountsServer,
  withSchemaDefinition: false,
});

console.log(accountsGraphQL.typeDefs)
```
Will print 
```graphql
type TwoFactorSecretKey {
  ascii: String
  base32: String
  hex: String
  qr_code_ascii: String
  qr_code_hex: String
  qr_code_base32: String
  google_auth_qr: String
  otpauth_url: String
}

input TwoFactorSecretKeyInput {
  ascii: String
  base32: String
  hex: String
  qr_code_ascii: String
  qr_code_hex: String
  qr_code_base32: String
  google_auth_qr: String
  otpauth_url: String
}

input CreateUserInput {
  username: String
  email: String
  password: String
}

type Query {
  twoFactorSecret: TwoFactorSecretKey
  getUser: User
}

# ... all accounts types

schema {
  query: Query
  mutation: Mutation
}
```

@ardatan do you have an idea why?

**Comment by ardatan** [comment]
I think it is related to `@graphql-modules/epoxy`. It puts schema definitions at the end by default. 
@dotansimha what do you think?

**Comment by pradel** [comment]
Any update on this one? Currently it's not possible to use the graphql-api without graphql-modules :(

**Comment by ardatan** [comment]
Could you try with canary version of graphql-modules?
`0.3.0-alpha.d2db21bc`

**Comment by pradel** [comment]
I tried with version `0.2.10` and it looks like now `accountsGraphQL.typeDefs` return a `DocumentNode` type and not anymore a string

**Comment by pradel** [comment]
So I can't use it anymore like this:
```
const typeDefs = [
  `
  type Query {
    myQuery: String
  }

  type Mutation {
    myMutation: String
  }

  schema {
      query: Query,
      mutation: Mutation
  }
  `,
  accountsGraphQL.typeDefs,
];
```

**Comment by pradel** [comment]
I just created a pr with a failing test so you can check :) https://github.com/accounts-js/accounts/pull/508

**Comment by ardatan** [comment]
Actually, you can print `DocumentNode` using `print` function from `graphql` package like 
```
print(accountsModule.typeDefs)
```
But isn't it possible to use string and DocumentNode together in array while passing it through Apollo Server?

**Comment by ardatan** [comment]
@pradel Can we close this issue?
