### ISSUE TITLE
Improve accounts site landing page

### ISSUE THREAD

**Issue by TimMikeladze** [accounts-js/accounts#511]
Currently it just has placeholders and looks like so:

@pradel Any ideas on what to list as features? I'm thinking:

- GraphQL and Apollo integration
- REST support
- Passwords, OAuth, and 2FA. Maybe listing what oauth providers we support.
- React (when I finish that PR)

![image](https://user-images.githubusercontent.com/702718/49260076-c9e92300-f3f0-11e8-8ac5-dfa8ef1c0780.png)

**Comment by pradel** [comment]
Sounds good ! But don't know if we want to feature Oauth since it's not really finished for now
