### ISSUE TITLE
API doc issue - db should not be documented as optional in AccountsBoostOptions

### ISSUE THREAD

**Issue by miller-productions** [accounts-js/accounts#512]
The API doc for AccountsBoostOptions states:

```<<Optional>> db```

See: https://accounts-js.netlify.com/docs/api/boost/api-interfaces-accountsboostoptions#optional-db

This appears to be incorrect since...

```AccountsBoostOptions extends AccountsServerOptions {```

and in AccountsServerOptions 

```
if (!this.options.db) {
  throw new Error('A database driver is required');
}
```

**Comment by TimMikeladze** [comment]
`@accounts/boost` tries to automatically load the database driver package and initialize it so you don't need to explicitly pass it in, however a user can still choose to explicitly pass in `options.db` if they want to override the default behavior.

**Comment by miller-productions** [comment]
Thanks for the clarification Tim, that helps me understand it better.  Much appreciated.

Initially when I started playing around with ```@accounts/boost``` for the first time I got that error and was a bit confused.

After you explained it to me, I can now see that this is the reason...

```
const defaultAccountsBoostOptions = {
  storage: {
    uri: 'mongodb://localhost:27017',
    name: 'accounts-js',
  },
};
```

That makes sense.

Perhaps one idea to solve it could be to include a line in the doc called ```pre-requisitses``` or perhaps ```dependencies``` that states you must have Mongodb installed locally in order for ```@accounts/boost``` to work with its default settings. 

It is obvious when you go looking through the code that you need Mongodb, but not so obvious if you have only read the getting started guide and started browsing through some of the API docs.

**Comment by TimMikeladze** [comment]
https://github.com/accounts-js/accounts#getting-started-with-accountsboost

See the "Choose your database database driver" section where it points out that you need to install a db package.

If you think it can be made clearer please send a PR. I'm closing this issue.
