### ISSUE TITLE
Unable to set public claims for the generated user token

### ISSUE THREAD

**Issue by haydermabood** [accounts-js/accounts#542]
After checking the code I found that its not possible to set public claims for the generated tokens. Currnely `jwt.sign` received static list of data attributes: 

`
 const jwtData: JwtData = {
      token,
      isImpersonated,
      userId,
    };
`

What I want to do is to set some specific public claims according to user data, for example, 

`
const additionalClaims = {
  premiumAccount: true
};
`

Then, use those values inside resolvers logic.

It would be great if the framework can provide some kind of hook to provide additional token claim context and access those values within resolvers.

Thanks

**Comment by orinokai** [comment]
I'm also very interested in this feature. I have extended the User type to add a 'role' field and it would be great to add this as a claim in the JWT token. This would allow authorization on other services simply by decoding the token and checking the user role, without having to call getUser on the authentication server. Thanks!

**Comment by gbouteiller** [comment]
Any news about it?
