### ISSUE TITLE
createAccountsGraphQL is undefined

### ISSUE THREAD

**Issue by SachaG** [accounts-js/accounts#603]
Doing:

```
import { createAccountsGraphQL } from '@accounts/graphql-api';
console.log(createAccountsGraphQL)
```

Gives me `undefined`. 

Are the docs out of date on this? See https://github.com/accounts-js/accounts/blob/f7e45b8b22e573e911bf030cfea979ec019498e0/packages/graphql-api/README.md

**Comment by SachaG** [comment]
Oh ok I see that I was on the wrong commit somehow. Maybe there's a link somewhere else in the docs to a specific commit and that took me to the wrong place? Weird… Anyway I'll close this for now.

**Comment by pradel** [comment]
That's weird, I took a quick look and can't find this link 🤔

**Comment by pradel** [comment]
@SachaG can we close this one ?

**Comment by SachaG** [comment]
Yes sorry!
