### ISSUE TITLE
Unable to configure accountsjs with typeorm

### ISSUE THREAD

**Issue by lihaibh** [accounts-js/accounts#616]
I receive an error saying:
Data type "jsonb" in "UserService.options" is not supported by "sqlite" database

In the class UserService there is a field that is a json type and my database is sqlite.
is it possible somehow to make it work with sqlite database?

**Comment by pradel** [comment]
Hey @lihaibh for now the typeorm adapter support only postgresql, see https://github.com/accounts-js/accounts/issues/614#issuecomment-473262871
