### ISSUE TITLE
Entering an email as a username throws an error

### ISSUE THREAD

**Issue by elie222** [accounts-js/accounts#635]
The error message shown when entering an email for a username is that a username or email is required. Made it hard for us to debug as a username had been submitted.

**Comment by derblitz** [comment]
I can confirm that the following DOES NOT work:

mutation Register {
  createUser(user: { email: "a@b.com", password: "1234567", profile: {firstName: "a", lastName: "b"} })
}


However, this DOES work:

mutation CreateUser {
  createUser(user: { email: "a@b.com", password: "1234567", profile: {firstName: "a", lastName: "b"} })
}

**Comment by pradel** [comment]
The createUser function will throw if the username does not pass the [default username validation function](https://github.com/accounts-js/accounts/blob/master/packages/password/src/accounts-password.ts#L77), the error message should be improved 👍

**Comment by elie222** [comment]
Thanks. Made a PR:
https://github.com/accounts-js/accounts/pull/646

Still needs some work.
