### ISSUE TITLE
'register' mutation seems not to exist 

### ISSUE THREAD

**Issue by derblitz** [accounts-js/accounts#642]
The example mutation shown here (https://github.com/accounts-js/accounts/tree/master/examples/graphql-server-typescript) seems not to work with the demo typescript graphql server example.
Graphql returns the error: "Cannot query field \"register\" on type \"Mutation\"."

This is the query I am referencing to:
mutation Register {
  register(user: { username: "user", password: "1234567" })
}

**Comment by pradel** [comment]
Yeah you are right the README was updated, check this pull request to see how to use it https://github.com/accounts-js/accounts/pull/643/files

**Comment by derblitz** [comment]
Thanks for the quick reply! However, the example still does not work as graphql now says "Username or Email is required". When using username instead of email it works though.

**Comment by derblitz** [comment]
But I can confirm THIS issue with the outdated doc is now solved. The second issue I just mentioned has already been reported by another user 4 days ago (https://github.com/accounts-js/accounts/issues/635).
