### ISSUE TITLE
Result JS lib file is uglified

### ISSUE THREAD

**Issue by dotansimha** [accounts-js/accounts#68]
Not sure if it's the best approach, since it's hard to debug, and the app that uses these packages should minify it's own code and it's dependencies... 

@TimMikeladze what do you think?

**Comment by TimMikeladze** [comment]
I agree. The entire build / publish process could stand to be improved.

Mind sending a PR?

**Comment by davidyaha** [comment]
We use ts now.. we do publish the map files don't we?
