### ISSUE TITLE
Community Discussion Channel

### ISSUE THREAD

**Issue by Aervue** [accounts-js/accounts#691]
I'm a new fan of this project, I intend to do my own contributions in the near future. I'm thinking it would be great to have an open discussion community channel, would be great exposure on getting more people on board. I've tried joining the Slack but it's closed access and while I contacted various team members for an invite I was unsuccessful.

So maybe open Slack to everyone or create a discord channel ? (I think discord is better)

**Comment by pradel** [comment]
Hey @Aervue welcome 👋 

I will need your email in order to send you a slack invitation (you can post it there or send me a private message on [twitter](https://twitter.com/leopradel) if you prefer)

**Comment by pradel** [comment]
@agustif do you want a slack invitation?

**Comment by Aervue** [comment]
I'll send the email later today, why not just open it to public tho ?

**Comment by pradel** [comment]
Is it possible with slack ?

**Comment by agustif** [comment]
> @agustif do you want a slack invitation?
@pradel 
OMG Yes thank you, I actually found the link to the slack channel, but was to shy to ask for the invitation or open an issue about it haha

**Comment by agustif** [comment]
> Is it possible with slack ?

There are workarouds, no official way though: https://github.com/outsideris/slack-invite-automation

@pradel I twitted you asking DM to send you the email!

**Comment by Aervue** [comment]
@pradel My email is aervue.dev@gmail.com

**Comment by pradel** [comment]
@Aervue we also created a spectrum community https://spectrum.chat/accounts-js
