### ISSUE TITLE
Ant Design Pro / umi / dva example with accounts frontend example.

### ISSUE THREAD

**Issue by agustif** [accounts-js/accounts#692]
I'm planning to use this myself, I was wondering if anyone would be interested on my trying to extract an example/boilerplate from my current project when it's done! 

Anyway, since I've been toying around with ant.design.pro and it's accompanying suite of tools. (umi, dva, etc). It seems like a good choice compromise between CRA and NextJS. Talking about next, Once I move one from the admin to the customer-facing side of code, I might want to contribute a login working properly with NextJS, SSR, Cookies, and what not. Since the SSR rendering of things may imply some stuff in order to render a custom view based on cookies/http headers/context/props etc.

I was wondering if you know of any open source projects/code using currently both this together, but I haven't found any to see how it's done, So I might give it a try myself and share back once successful!

**Comment by pradel** [comment]
A next.js example sounds really great I think you can store the jwt in a cookie to be able to read it from the server and load the user data during ssr

**Comment by agustif** [comment]
Now that nextjs9 is out, with dynamic routings and what not, I hope I can tackle both of them as examples soon!

**Comment by agustif** [comment]
I do have things working with my ant.design.pro-layout based project. Once I finish I will try to separate code up and publish as example. should be a great pairing and as ant design comes only with a mock auth, it could very well end up being a default auth-module-plugin for ant.design.pro (Both projects are TS, and both projects make a lot of sense if you're trying to get an admin panel by yourself out to the world soon but safely.

Will open up a PR once it's decent enough.

For now haven't had time to look at next9, if anyone want's to give it a try, please be my guest! I might be staying with full umi/dva for my customer-facing project too anyway!

**Comment by eliasjohansson** [comment]
Currently trying to integrate accounts.js into a next9 TS project. If anyone have some tips it would be greatly appreciated. Might contribute with an example once ive figured it out.

**Comment by agustif** [comment]
@eliasjohansson That's awesome, can't wait to see/play with it.

Not much of a tip but I would start trying to do something with @accounts/apollo-link since next has always had good docs on examples/with-apollo

I think you pretty much need to figure out how to store the userSession in cookies and not localStorage/jwt, so SSR can be done with userAuth and what not

Maybe someone who knows the project and next better can have greater feedback for you!
