### ISSUE TITLE
Best practices - unique link authentication

### ISSUE THREAD

**Issue by derblitz** [accounts-js/accounts#698]
I'm using accounts-js with graphql for authentication already. Now I would like my users to be able to send out invitation emails to other users. These emails should include a unique link that let's the owner of that link access specific parts of the application without actually being registered.

Are there some best practices for that?

My only idea would be to create a user (with the unique link as username and and no password) for each unique link I create so when the unique link is opened, I use the accounts-js client to login with that username (which is the unique link string - e.g. sdfio2389r789ds89sd796w379e789ds789sdf89sd89f89sd89). If this is the best way to do it, should I use the accounts-js client ON THE SERVER in order to create this unique link user?

**Comment by pradel** [comment]
If I understand your problem correctly I think you can create a new user on the server linked to the email you are sending the message to, then you can generate a new session on the server for the freshly created user and attach the tokens as url params. Then when the user click on the link the client can extract the tokens from the url and set them in the localstorage.

**Comment by derblitz** [comment]
Great, thanks for your answer!!! I'll close the issue.
