### ISSUE TITLE
Accounts config options

### ISSUE THREAD

**Issue by TimMikeladze** [accounts-js/accounts#7]
The following config options have been implemented
- [x] title
- [ ] requestPermissions
- [ ] requestOfflineToken
- [ ] forceApprovalPrompt
- [ ] requireEmailVerification
- [ ] passwordSignupFields
- [ ] minimumPasswordLength
- [x] loginPath
- [x] signupPath
- [ ] resetPasswordPath
- [x] profilePath
- [ ] changePasswordPath
- [x] homePath
- [ ] onSubmitHook
- [ ] onPreSignUpHook
- [ ] onPostSIgnUpHook
- [ ] onEnrollAccountHook
- [ ] onResetPasswordHook
- [ ] onVerifyEmailHook
- [x] onSignedInHook
- [ ] onSignedOutHook
- [ ] sendVerificationEmail
- [x] forbidClientAccountCreation
- [ ] restrictCreationByEmailDomain
- [ ] loginExpirationInDays
- [ ] oauthSecretKey
- [ ] passwordResetTokenExpirationInDays
- [ ] passwordEnrollTokenExpirationInDays

**Comment by davidyaha** [comment]
I think this is stale issue.
closing.
