### ISSUE TITLE
Rest/Express (get) /user is a POST handler

### ISSUE THREAD

**Issue by stevokk** [accounts-js/accounts#705]
I didn't want to open a pull request without confirmation that this is a mistake and not intended behaviour. 

Currently the express package registers the get current user endpoint /user as a POST only handler, what is the meaning behind this? I couldn't get the demo react application without editing this within the node_modules.

See file: https://github.com/accounts-js/accounts/blob/master/packages/rest-express/src/express-middleware.ts#L32

Thanks for the library, hopefully I can contribute back once I'm up to speed.

**Comment by TimMikeladze** [comment]
Are you referring to this line in the example https://github.com/accounts-js/accounts/blob/master/examples/react-rest-typescript/src/Home.tsx#L25 ?

If so, it should be switched to use a POST request, that's an error in the example.

**Comment by stevokk** [comment]
Is there a reason to restrict this to a POST only? If an Authorization header is passed then you don't need a request body, and therefore able to do this with a GET

I did some quick reading of other implementations and a GET requests seems to be used so it won't be against the spec I hope.

https://www.oauth.com/oauth2-servers/signing-in-with-google/verifying-the-user-info/

Thank you for your response

**Comment by TimMikeladze** [comment]
Based on my understanding you are correct, there is no reason why we couldn't accept GET requests. This is a relatively simple fix and seems like you already fixed it manually in your node_modules. Do you mind sending a PR?

**Comment by stevokk** [comment]
Please see: https://github.com/accounts-js/accounts/pull/708
