### ISSUE TITLE
Use custom field validators

### ISSUE THREAD

**Issue by TimMikeladze** [accounts-js/accounts#74]
Per discussion with @davidyaha in #72 

At the moment the validation rules for each field (username, password, email) are handled within `validators.js` in the `@accounts/common`. These should be configurable via the accounts config so consumers could define their own validation rules for fields. 

The default password field validators should also take into account the minimum password length requirements.

Thoughts on validating password complexity?

**Comment by davidyaha** [comment]
Was fixed with the latest password package
