### ISSUE TITLE
Documentation for REST seems lacking compared to GraphQL

### ISSUE THREAD

**Issue by tokeskovgaard** [accounts-js/accounts#742]
First of all, thank you for all the work in this package! It is a pearl.

I have used your package with the graphql transport layer and everything worked. 
I recently decided to use the REST transport layer for another solution, but ran into some problems with understanding how to alter the user model. Is it possible with REST? I am using a Mongo database but couldn't find a good place to extend the schema.

The documentation for GraphQL is here: https://accounts-js.netlify.com/docs/transports/graphql
The corresponding documentation for REST is here: https://accounts-js.netlify.com/docs/transports/rest

**Comment by pradel** [comment]
Hey @tokeskovgaard yeah the REST api is not as good as the graphql one :(
You can take a look at the examples for now 
https://github.com/accounts-js/accounts/tree/master/examples/rest-express-typescript
https://github.com/accounts-js/accounts/tree/master/examples/react-rest-typescript
You can ask questions on the spectrum chat :) https://spectrum.chat/accounts-js

**Comment by tokeskovgaard** [comment]
Thanks for the reply
