### ISSUE TITLE
Accounts-js with websocket?

### ISSUE THREAD

**Issue by vrecluse** [accounts-js/accounts#743]
When I use subscription everything about accounts-js has broken.
Any examples?

**Comment by pradel** [comment]
Hey, can we have a bit more context about your issue?
Are you using REST or GraphQl?
Is it working if you don't have websocket enabled?

**Comment by vrecluse** [comment]
I'm using GraphQL,
It's working if I don't have websocket enabled.
But when I link apollo-link-ws, It throws unauthorized error.
On the server, the contex in initialize params is: context: ({ req }) =>  accounts.context({ req }
But req is undefined when I switch to websocket.

**Comment by vrecluse** [comment]
ok, I solved this problem by the following code: 
client:
```ts
const subscriptionMiddleware = {
  applyMiddleware: async (options: any, next: any) => {
    options.authToken = await accountsClient.getTokens();
    next();
  },
};

// add the middleware to the web socket link via the Subscription Transport client
(websocketLink as any).subscriptionClient.use([subscriptionMiddleware]);
```
server:
```ts
    context: async ({ req, payload }: any) =>  { 
        if (payload && payload.authToken) {
            const user = await accountsServer.resumeSession(payload.authToken.accessToken);
            return { user }
        } else {
            const ctx = await accounts.context({ req });
            return ctx;
        }
    }
```

**Comment by gisderdube** [comment]
Amazing! Was looking for exactly this. Thanks a bunch for sharing your solution 😃
