### ISSUE TITLE
Automatic log out after a certain amount of time

### ISSUE THREAD

**Issue by elie222** [accounts-js/accounts#748]
In a project of ours users are being logged out after a certain amount of time (maybe 30 minutes).

This is actually okay as the client wants it, but I need to hook into that log out event and not finding it in the code. Any pointers? Is there an auto log out mechanism built in or is this happening some other way I'm not aware of?

**Comment by pradel** [comment]
You are right the default session time is 30 minutes, but you can overwrite it to make it work for your needs, for example :
```js
const accountsServer = new AccountsServer({
	# ... your config
	tokenConfigs: {
      accessToken: {
        expiresIn: '10m',
      },
      refreshToken: {
        expiresIn: '5d',
      },
    },
})
```

**Comment by elie222** [comment]
Is there a way to hook into the timeout event, to refresh the page at that time? Or I should just handle that myself?

**Comment by pradel** [comment]
For now you can get the tokens from the client and check when the token will expire manually like this https://github.com/accounts-js/accounts/blob/255b6cf180bd029c13f4a9893c99398b6bca8a7e/packages/client/src/utils.ts#L8-L12

**Comment by elie222** [comment]
> You are right the default session time is 30 minutes, but you can overwrite it to make it work for your needs, for example :

Turns out the default is 90 minutes:
https://github.com/accounts-js/accounts/blob/master/packages/server/src/accounts-server.ts#L30

I'm a little confused about the refresh token though. If set for 7 days, will the client not automatically use that and refresh the access token itself?

**Comment by pradel** [comment]
Hey yes you are right sorry it's 90 minutes.
So the `refreshSession` method on the client should refresh the tokens automatically.
https://github.com/accounts-js/accounts/blob/255b6cf180bd029c13f4a9893c99398b6bca8a7e/packages/client/src/accounts-client.ts#L105-L131

Are you using graphql or rest to query your backend?
How do you inject the tokens in the headers?

**Comment by pradel** [comment]
Are you using `apollo-link-accounts` to inject the token?

**Comment by elie222** [comment]
> Are you using graphql or rest to query your backend?
GraphQL

> How do you inject the tokens in the headers?
Regular AccountsJS (we don't touch headers ourselves). See below.

> Are you using apollo-link-accounts to inject the token?
No

This is the file with all our Apollo Client and AccountsJS code:

```ts
import { ApolloClient } from 'apollo-client'
import { ApolloLink } from 'apollo-link'
import { createUploadLink } from 'apollo-upload-client'
import { InMemoryCache } from 'apollo-cache-inmemory'
import { AccountsGraphQLClient } from '@accounts/graphql-client'
import { AccountsClientPassword } from '@accounts/client-password'
import { AccountsClient } from '@accounts/client'
import { accountsLink } from '@accounts/apollo-link'
import { GRAPHQL_URL } from './settings'

const httpLink = createUploadLink({
  uri: GRAPHQL_URL,
})

const cache = new InMemoryCache()

// accounts js
export const graphQLApolloClient = new ApolloClient({
  link: ApolloLink.from([httpLink]),
  cache,
})

export const accountsGraphQL = new AccountsGraphQLClient({
  graphQLClient: graphQLApolloClient,
  userFieldsFragment: `
    fragment userFields on User {
      id
      username
      emails {
        address
        verified
      }
      roles
    }
  `,
})
export const accounts = new AccountsClient({}, accountsGraphQL)
export const accountsPassword = new AccountsClientPassword(accounts)

// regular apollo client
const authLink = accountsLink(() => accounts)

export const client = new ApolloClient({
  link: ApolloLink.from([authLink, httpLink]),
  cache,
})
```

**Comment by pradel** [comment]
I see so that's why the tokens are not refreshed, I think we should replace this line https://github.com/accounts-js/accounts/blob/master/packages/apollo-link-accounts/src/index.ts#L10 by `refreshSession` in the @accounts/apollo-link package, that way the tokens will be refreshed automatically.

**Comment by elie222** [comment]
Ok. I can make a PR with that now. I should be using `apollo-link-accounts` in my project?

**Comment by elie222** [comment]
I made the PR. But I'm wondering, does it make sense to refresh the token on every request?

**Comment by elie222** [comment]
For anyone else that runs into this in the future. I solved my original problem as follows:

I use a 30 second interval that I placed inside my `UserProvider` that checks for expiration:

```ts
import * as React from 'react'
import { isTokenExpired } from '@accounts/client/lib/utils'
import { accounts, accountsGraphQL, accountsPassword } from '../../utils/apollo'

  React.useEffect(() => {
    // check every 30 seconds if log in token is still valid
    const handle = setInterval(async () => {
      const tokens = await accounts.getTokens()

      if (tokens && isTokenExpired(tokens.accessToken)) {
        console.log('Access token expired. Logging out')
        logOut()
      }
    }, 30000)
```
