### ISSUE TITLE
Mikro-ORM database adapter

### ISSUE THREAD

**Issue by NickBolles** [accounts-js/accounts#767]
[Mirko-ORM](https://github.com/B4nan/mikro-orm) is a cool alternative to TypeORM, that I feel works better in several respects. 

having a database adapter for Mikro-ORM would be awesome.

**Comment by darkbasic** [comment]
I've made one: https://github.com/accounts-js/accounts/pull/1003

**Comment by darkbasic** [comment]
It's in master.
