### ISSUE TITLE
What this line mean? for testing only?

### ISSUE THREAD

**Issue by quaj** [accounts-js/accounts#771]
https://github.com/accounts-js/accounts/blob/d4db308b16765738339f7a7539eeed24755672e2/packages/graphql-api/src/utils/authenticated-resolver.ts#L7

**Comment by pradel** [comment]
If your application needs to bypass the `authenticated` directive logic you can set this option, it can be for testing purposes or if you want to apply some custom logic and want this behavior to be disabled.
