### ISSUE TITLE
Bug within examples react-graphql-typescript

### ISSUE THREAD

**Issue by Nrin3141** [accounts-js/accounts#778]
When I used the code, that you provide in the example I noticed a weird bug/behavior. When trying to log in a newly created user, the login fails, saying that the wrong password was provided. 
When the same authenticate mutation is executed via the GraphiQl playground it works out fine.

Possible cause/workaround: There is a small difference between the method used in the examples login file: 
```js
try {
      await accountsPassword.login({
        user: {
          email,
        },
        password,
        code,
      });
      history.push('/');
    } catch (err) {
      setError(err.message);
}
```

and the examples signup file: 
```js
try {
      await accountsGraphQL.createUser({
        email: user.email,
        password: user.password,
        profile: {
          firstName: user.firstName,
          lastName: user.lastName,
        },
      });
      history.push('/login');
    } catch (err) {
      setError(err.message);
}
```

one uses the `accountsGraphQL.createUser` and the other one the `accountsPassword.login` method... If both use the same methods from either `accountsPassword` or `accountsGraphQl` things work out fine though. 

This happens because `accountsPassword` is hashing the passwords on the client-side but `accountsGraphQl` is not. Therefore it might be better to use `accountsPassword` within the example. 

This is related to #649

**Comment by pradel** [comment]
@Nrin3141 Thanks for the detailed issue, since v0.19.0 we removed the client side hashing of the password by deafult, see https://github.com/accounts-js/accounts/releases/tag/v0.19.0.
So new users won't encounter the same problem now.
