### ISSUE TITLE
doesn't work on serverless any more

### ISSUE THREAD

**Issue by sakulstra** [accounts-js/accounts#792]
The strict dependency on `graphql-modules` https://github.com/accounts-js/accounts/blob/master/packages/graphql-api/package.json#L36 breaks serverless deployments atm.

Any chance of softening the version constraints? and/or to offering a graphql-modules less version?
https://github.com/Urigo/graphql-modules/issues/649

<3

As a reproduction you could try deploying one of the examples with zeit/now i guess.

**Comment by agustif** [comment]
https://github.com/Urigo/graphql-modules/issues/649#issuecomment-527310807

It seems it's been fixed 6h ago by graphql-modules maintainers, You can confirm you have no problems? Not sure if you would need to update or wait for a new release which uses the new 0.7.11 graphql-modules.

Either wait for it, or try to upgrade yourself and see if it's fixed for your code or not with that!

**Comment by sakulstra** [comment]
sorry forgot to answer, seems to work again :+1: still curious if i can somehow import this without wrapping things in graphql-modules :thinking:
