### ISSUE TITLE
🍪add cookieStorage for Tokens

### ISSUE THREAD

**Issue by agustif** [accounts-js/accounts#807]
https://www.npmjs.com/package/cookie-storage
Let's add 🍪Token Storage. so #802 and #804 can be resolved!

Thankfully there's already a package for that!
https://www.npmjs.com/package/cookie-storage

utils/accounts.ts
```
import { AccountsClient } from '@accounts/client';
import { AccountsClientPassword } from '@accounts/client-password';
import GraphQLClient from '@accounts/graphql-client';
import ApolloClient from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { HttpLink } from 'apollo-link-http';
import fetch from 'isomorphic-fetch';
import { CookieStorage } from 'cookie-storage';

const cookieStorage = new CookieStorage();
const link = new HttpLink({
  uri: 'http://localhost:4000/graphql',
  fetch,
});
const cache = new InMemoryCache();
const apolloClient = new ApolloClient({
  link,
  cache,
});

const accountsGraphQL = new GraphQLClient({ graphQLClient: apolloClient });
const accountsClient = new AccountsClient(
  {
    // We tell the accounts-js client to use cookieStorage to store the tokens
    cookieStorage,
  },
  accountsGraphQL
);

const accountsPassword = new AccountsClientPassword(accountsClient);

export { accountsClient, accountsGraphQL, accountsPassword, apolloClient };
```
sadly trying to add tokenStorage: cookieStorage doesn't work.
<img width="1046" alt="Screenshot 2019-09-16 at 18 09 42" src="https://user-images.githubusercontent.com/6601142/64975047-6b713080-d8ae-11e9-8e58-7d8f19627c10.png">

I will submit a PR for accounts/client basically cloning the token-local implementation to add a cookieStorage option!

I will also change the separator for the name, since : or semicolon's don't look nice in cookies it seems!
<img width="1636" alt="Screenshot 2019-09-16 at 01 21 09" src="https://user-images.githubusercontent.com/6601142/64975341-108c0900-d8af-11e9-8aba-934feb1c64d3.png">

Hopefully this is OK, not sure if much of a breaking change or something!

**Comment by stolinski** [comment]
Yes please.

**Comment by agustif** [comment]
Hi @stolinski I actually have some version of working in my PR #804, you can take a look and give any feedback!

I actually messed up my local code, but I had it working all way down with SSR rendered homepage by reading cookies.

Hopefully someone else can clean it up and merge it to master!

**Comment by agustif** [comment]
Screenshots from PR #804 
I think this are the most relevant changes for CookieStorage to work.

<img width="554" alt="Screenshot 2019-09-16 at 19 35 41" src="https://user-images.githubusercontent.com/6601142/64980001-3e764b00-d8b9-11e9-825e-03ace38df4c8.png">
<img width="755" alt="Screenshot 2019-09-16 at 19 33 51" src="https://user-images.githubusercontent.com/6601142/64980004-3e764b00-d8b9-11e9-82c6-80d3fd4b8016.png">
<img width="778" alt="Screenshot 2019-09-16 at 19 33 39" src="https://user-images.githubusercontent.com/6601142/64980005-3e764b00-d8b9-11e9-9a53-ff87b5c7b60e.png">
