### ISSUE TITLE
Allow customization on hashing of password

### ISSUE THREAD

**Issue by kevinlaw91** [accounts-js/accounts#811]
_**TLDR:** Allow us to specify a custom `hash` function and a `verify` function in config_

Currently the `@accounts/password` package chose `bcrypt` as the hashing method. This is a good default, but imo we should be allowed to customize it, so that we can use `argon2` etc.

**Comment by pradel** [comment]
This sounds like a good idea yes 👍 
We could add the following options to the password package:
```ts
bcryptPassword: async (password: string) => Promise<string>;
verifyPassword: async (password: string, hash: string) => Promise<boolean>;
```
