### ISSUE TITLE
Documentation and examples of Authenticating are diferent

### ISSUE THREAD

**Issue by gnunesmoura** [accounts-js/accounts#816]
At the [authenticating-resolvers](https://accounts-js.netlify.com/docs/api/graphql-api/api-readme#authenticating-resolvers) the docs uses this call
`authenticated(AccountsServer, function)`

At the [authenticated](https://accounts-js.netlify.com/docs/api/graphql-api/api-readme#authenticated) doc it show the method signature as 
`authenticated(function)`

I think that the right one is the authenticated documentation, could you change the exemples to make easier to new users use the API?

**Comment by pradel** [comment]
Yeah, you are right!
Pull requests welcome to fix the documentation :)

**Comment by deathemperor** [comment]
There're also some other issues with the docs, right at the getting started. This code doesn't work:

```js
import accountsBoost from `@accounts/boost`;
(async () => {
  const accounts = await accountsBoost({
    tokenSecret: 'your secret'
  }).listen({
    port: 4003
  });
})();
```

Also, @accounts/oauth-facebook doesn't exist.

**Comment by gezquinndesign** [comment]
@pradel I'm happy to submit a PR for both of these issues if no one else is looking at them?

**Comment by JoJ123** [comment]
I came over the same.
PR raised: https://github.com/accounts-js/accounts/pull/1056

**Comment by gezquinndesign** [comment]
Hello all,

Sorry I'm so late (!) in actually getting round to this!  I see JoJ123 fixed the original issue.  I tried looking at the issue raised by deathemperor but can't see a good working example of the minimal code required to start an `@accounts/boost` server. Any pointers?
