### ISSUE TITLE
Client-password typings incorrect

### ISSUE THREAD

**Issue by NickBolles** [accounts-js/accounts#818]
The parameters for [createUser](https://github.com/accounts-js/accounts/blob/master/packages/client-password/src/client-password.ts#L20) and maybe [login](https://github.com/accounts-js/accounts/blob/master/packages/client-password/src/client-password.ts#L28), should be updated to be [PasswordCreateUserType](https://github.com/accounts-js/accounts/blob/master/packages/password/src/types/password-create-user-type.ts#L4) and maybe [PasswordLoginType](https://github.com/accounts-js/accounts/blob/master/packages/password/src/types/password-login-type.ts#L4) respectively?

createUser doesn't fail because of the index type on the CreateUser type. But it's probably more correct.

**Comment by pradel** [comment]
You are right, thanks for reporting 👍
