### ISSUE TITLE
General Questions on the Roadmap of this project

### ISSUE THREAD

**Issue by ElectricCookie** [accounts-js/accounts#82]
I just stumbled on this repo while looking for an account management library for a project. I really like the idea of having all of this effort of setting up authentication being handled by a library.

Now I've seen that this is under heavy development  and was wondering if there's a time-line or an agenda what needs to be done / is the most urgent since I would love to contribute to this project!

Thanks in advance!

// edit just noted that this is similar to #20 . Maybe  setup some projects in github to make things clear?

**Comment by TimMikeladze** [comment]
Hi @ElectricCookie 

There isn't a timeline but agenda wise our priority right now is a documentation effort. The project is under heavy development but it's also being consumed in our apps so it's certainly ready to be used. The only blocker is knowing how to get it up and running. If you're looking to contribute there are issues of varying degrees across the organization's repos let me know, if you have any questions about how to get started. You can also join the #js-accounts channel in the apollo slack.
