### ISSUE TITLE
user enumeration issue

### ISSUE THREAD

**Issue by sakulstra** [accounts-js/accounts#831]
I personally don't think that user enumeration at `signUp` is a big problem and for most applications I worked on the UX was more valuable then the risk of users figuring out if a certain email exists on our platform. I'd prefer some sort of rate limiting to protect against brute forcing over purposely-unhelpful error messages at signup.

That said, when trying to understand how the current user enumeration protection trough `ambiguousErrorMessages` works I got to the conclusion that it just *doesn't work* - at least not when using graphql-api and for `createUser` -> I would expect it to not work for other graphql mutations as well.

The problem seems to be that `graphql-api` just throws, but doesn't catch certain types of error so e.g. https://github.com/accounts-js/accounts/blob/master/packages/graphql-api/src/modules/accounts-password/resolvers/mutation.ts#L19 is never actually executed when https://github.com/accounts-js/accounts/blob/master/packages/graphql-api/src/modules/accounts-password/resolvers/mutation.ts#L18 throws.
I think this is related to the last checkbox in #181.
cc: https://github.com/accounts-js/accounts/pull/525#issuecomment-538910169 @pradel

**Comment by acomito** [comment]
You could technically store a signup attempts field on the User record (or somewhere else) and check that in one of the signup/login hooks?

**Comment by sakulstra** [comment]
@acomito sorry for the delayed answer. I don't see why not, but I also don't see how this relates to the problem.

If you wanted to solve the bug I described here I guess the "simple solution" would be to guard the throwing mutations like e.g. `createUser` from throwing the error to the client, so that https://github.com/accounts-js/accounts/blob/master/packages/graphql-api/src/modules/accounts-password/resolvers/mutation.ts#L19 has a chance of being evaluated.

**Comment by pradel** [comment]
Proposed fix for this issue: https://github.com/accounts-js/accounts/pull/914
