### ISSUE TITLE
[graphql-api] Unexpected reserved word 

### ISSUE THREAD

**Issue by stolinski** [accounts-js/accounts#836]
I'm getting an unexpected reserved word error with this line below.

`const accountsGraphQL = AccountsModule.forRoot({ accountsServer })`

Error
```
/Users/scotttolinski/Sites/levelup/node_modules/@accounts/graphql-api/node_modules/graphql-toolkit/dist/commonjs/loaders/load-typedefs.js:109
W20191015-08:49:34.161(-6)? (STDERR)         for await (let path of globby.stream(foundGlobs, { cwd, absolute: true })) {
W20191015-08:49:34.161(-6)? (STDERR)             ^^^^^
W20191015-08:49:34.162(-6)? (STDERR)
W20191015-08:49:34.162(-6)? (STDERR) SyntaxError: Unexpected reserved word
W20191015-08:49:34.163(-6)? (STDERR)     at createScript (vm.js:80:10)
W20191015-08:49:34.163(-6)? (STDERR)     at Object.runInThisContext (vm.js:139:10)
W20191015-08:49:34.163(-6)? (STDERR)     at Module._compile (module.js:617:28)
W20191015-08:49:34.164(-6)? (STDERR)     at Module.Mp._compile (/Users/scotttolinski/Sites/levelup/.meteor/local/build/programs/server/runtime.js:50:23)
```

Some background, this error is occurring in our Meteor migration, where we're running a Meteor site that's using Mongoose. I understand this might be a very odd use case, but we're using async/await all over with no issues.

**Comment by derblitz** [comment]
Which node version are you using? Please check with node --version.

**Comment by derblitz** [comment]
Make sure it's something > V8.6.3. Most Ubuntu version ship with some older 8.X version which would explain the error: See https://github.com/nodejs/node/issues/17530

**Comment by stolinski** [comment]
Currently on `8.11.4` via Meteor 1.8.2

I'm totally aware this could be something Meteor related, but this is the only package or instance using await that's having any issue, so I figured I'd start here.

**Comment by derblitz** [comment]
It's not an await issue. It's about "for await" --> async iterators.
Any chance you can try updating node to eg. version 11?

**Comment by ardatan** [comment]
@stolinski Check here;
https://github.com/ardatan/graphql-toolkit/issues/259#issuecomment-538556390

**Comment by stolinski** [comment]
@derblitz  understood. Unfortunately with Meteor that's not a simple task. The only version running a newer Node is in beta and currently failing our build.

@ardatan Ah, that looks about right, looks like @accounts/graphql-api isn't pulling in the latest. Submitted a pr https://github.com/accounts-js/accounts/pull/837

**Comment by stolinski** [comment]
I'm using 0.5.17 in my local code for accounts-js and the error is gone, so I can confirm the issue is solved by updating that version on graphql-toolkit

**Comment by pradel** [comment]
Will be included in the next version, thanks @stolinski
