### ISSUE TITLE
[@accounts/apollo-link] accountsClient.refreshSession() causes infinite loop

### ISSUE THREAD

**Issue by stolinski** [accounts-js/accounts#839]
This is tough one to debug. When using `authLink` I'm getting infinite loops and browser tab crashing after stopping and resuming my dev server.

I'm using authLink like this

```
const authLink = accountsLink(() => accountsClient)
const httpLink = new HttpLink({
  uri: '/graphql',
})

const cache = new InMemoryCache()
const client = new ApolloClient({
  link: from([authLink, httpLink]),
  cache,
  resolvers,
})
```

I'm not getting anything from the browser's profiler because it crashes out. If I comment out the authLink, the client loads, re-add it and everything works as expected until I stop and restart my dev server.

No errors or anything odd present on the server. 

Any thoughts here? Has only started happening since adding the authLink, but I honestly have no clue on the cause here. Any ideas on the best way to troubleshoot this?

**Comment by stolinski** [comment]
Looks like it has something to do with `isTokenExpired` as shown by the selected box in the flame graph image. I'm uploading the profile right now, but it's pretty intense, so I've taken a screenshot in the meantime. 

<img width="1423" alt="Screen Shot 2019-10-17 at 3 57 21 PM" src="https://user-images.githubusercontent.com/669383/67050906-e4a2b400-f0f6-11e9-8a44-148f346814c1.png">

**Comment by stolinski** [comment]
<img width="1412" alt="Screen Shot 2019-10-17 at 4 04 17 PM" src="https://user-images.githubusercontent.com/669383/67051248-d30ddc00-f0f7-11e9-8dec-82b05fc10cb8.png">

It's basically this, over and over.

Here is the profile if anyone would like to take a look.
https://drive.google.com/open?id=18bFdTY7s5Zsmq51Dw5tHpTNncEO_NB45

**Comment by stolinski** [comment]
I've def nailed it down to the `const tokens = await accountsClient.refreshSession();` inside `@accounts/apollo-link` Removing this, fixes the loop. I've been reading about async apollo-link, but I'm not entirely sure where why the auth link is looping repeatedly without out ever completing the refreshSession though.

**Comment by stolinski** [comment]
I've managed to get a temporary working solution by omitting the refreshSession mutation from a custom version of the accounts link.

Here's what's working for me

```
import { setContext } from 'apollo-link-context';
import { ApolloLink } from 'apollo-link';
import { Tokens } from '@accounts/types';
import { AccountsClient } from '@accounts/client';

type AccountsClientFactory = () => AccountsClient | Promise<AccountsClient>;

let accountsClient: AccountsClient;
let tokens: Tokens | null;

export const accountsLink = (accountsClientFactory: AccountsClientFactory): ApolloLink => {
  return setContext(async (_, { headers: headersWithoutTokens }) => {

    if (!accountsClient) {
      console.log(accountsClient);
      accountsClient = await accountsClientFactory();
    }
    if (!tokens) {
      tokens = await accountsClient.getTokens();
    }
    const headers = { ...headersWithoutTokens }

    if (tokens) {
      headers.Authorization = 'Bearer ' + tokens.accessToken;
    }

    return {
      headers,
    };
  })
};
```

Basically added some caching and swapped our refreshTokens with a `await accountsClient.getTokens();` This 100% fixes the infinite loop, but at the cost of not refreshing our refreshToken. I'm sure this isn't the best solution for the reason mentioned, but it's working well for me.  Hopefully someone  with a deeper knowledge of this package can comment on a complete solution, but I'd assume that mutation is having the link re-fire in perpetuity.

**Comment by derblitz** [comment]
FYI: happened to me as well.

**Comment by stolinski** [comment]
I'd love guidance on this. I've tried to do some digging, but I'm not sure what the issue is here. I've only found one other person having an infinite loop with `apollo-link-context` and they said they needed an entirely different approach to refresh tokens.

**Comment by jpdewing** [comment]
Thinking out loud (and I am new to accounts-js).

I think the issue is that when the accessToken has expired and the refreshToken is still valid accountsClient.refreshSession will refresh the accessToken calling this.transport.refreshTokens, this in turn ends up calling a mutation that ends up re-running the authLink /accountLink code block.  accountsClient.refreshSession is called again and ends up in a loop.

**Comment by stolinski** [comment]
@jpdewing Thanks, this is verifiably what's happening. 

If calling a mutation from authLink is a no-go, what is the proper way to refresh the session within a Link?

**Comment by sakulstra** [comment]
not sure if this helps as i ditched accounts/client for other reason and am using next.js, but this custom implementation seems to work fine for me so it might be material for inspiration :sweat_smile: :
```
import { ApolloLink, Operation, NextLink } from "apollo-link";
import jwtDecode from "jwt-decode";
import lS from "./storage/localStorage";
import { StorageAdapter } from "./storage/interface";
import { REFRESH_TOKEN, REFRESH_TOKEN_CALLBACK } from "./mutations";
import { ApolloClient } from "apollo-client";

interface JwtDecodeData {
  exp: number;
  iat: number;
}
// take from aaccounts/client/utils
export const isTokenExpired = (token: string): boolean => {
  const currentTime = Date.now() / 1000;
  const decodedToken = jwtDecode<JwtDecodeData>(token);
  return decodedToken.exp < currentTime;
};

interface AccountsLink {
  storage: StorageAdapter;
  client: ApolloClient<any>;
  context: any;
}
class AccountsLink extends ApolloLink {
  constructor(props: { storage: any; context: any }) {
    super();
    this.storage = (props && props.storage) || lS;
    this.context = props.context;
  }

  injectClient = (client: ApolloClient<any>): void => {
    this.client = client;
  };

  request(operation: Operation, forward: NextLink) {
    if (!this.client) throw new Error("you have to provide a client");
    operation.setContext(({ headers = {} }: { headers: any }) => {
      const accessToken = this.storage.get("accessToken", this.context);
      const refreshToken = this.storage.get("refreshToken", this.context);
      // prevent infinite loop when refreshToken ripples trough this link
      if (operation.operationName === "refreshTokens") return headers;
      if (accessToken) {
        if (isTokenExpired(accessToken)) {
          if (refreshToken && !isTokenExpired(refreshToken)) {
            this.client
              .mutate({
                mutation: REFRESH_TOKEN,
                variables: { accessToken, refreshToken }
              })
              .then(REFRESH_TOKEN_CALLBACK(this.storage));
          } else {
            this.storage.remove("accessToken");
            this.storage.remove("refreshToken");
            return headers;
          }
        }
        return {
          headers: {
            ...headers,
            Authorization: "Bearer " + accessToken
          }
        };
      }
    });

    return forward ? forward(operation) : null;
  }
}

export default AccountsLink;
```

**Comment by thomasttvo** [comment]
@stolinski here's a solution that's similar to yours but still allows refreshing tokens.

Write a custom `accountsLink` function as followed:
```
import { setContext } from 'apollo-link-context'
import { ApolloLink } from 'apollo-link'

export const accountsLink = (accountsClientFactory): ApolloLink => {
  return setContext(async (req, props) => {
    const { headers: headersWithoutTokens } = props
    const accountsClient = await accountsClientFactory()
    const headers = { ...headersWithoutTokens }

    if (req.operationName !== 'refreshTokens') {
      const tokens = await accountsClient.refreshSession()

      if (tokens) {
        headers.Authorization = 'Bearer ' + tokens.accessToken
      }
    }

    return { headers }
  })
}
```

**Comment by pradel** [comment]
@thomasttvo thanks for commenting on the issue, this sounds like a great fix!

Happy to merge a pull request with the fix if somebody wants to help :)
