### ISSUE TITLE
await keyword reserved error

### ISSUE THREAD

**Issue by acomito** [accounts-js/accounts#842]
For me, this works
```
  "dependencies": {
    "@accounts/boost": "^0.19.0",
    "@accounts/graphql-api": "^0.19.0",
    "@accounts/mongo": "^0.19.0",
    "@accounts/password": "^0.19.0",
    "@accounts/server": "^0.19.0",
    "@graphql-modules/core": "^0.7.10",
    "apollo-server": "^2.4.8",
    "babel-cli": "^6.26.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "dotenv": "^8.0.0",
    "faker": "^4.1.0",
    "graphql": "^14.2.1",
    "graphql-toolkit": "^0.5.10",
    "graphql-tools": "^4.0.5",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "mongoose": "^5.5.9",
    "nodemailer": "^6.3.0",
    "unique-random-array": "^2.0.0"
  },
```

Where this gives me an error
```
  "dependencies": {
    "@accounts/boost": "^0.19.0",
    "@accounts/graphql-api": "^0.19.0",
    "@accounts/mongo": "^0.19.0",
    "@accounts/password": "^0.19.0",
    "@accounts/server": "^0.19.0",
    "@graphql-modules/core": "^0.7.13",
    "apollo-server": "^2.9.7",
    "babel-cli": "^6.26.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "dotenv": "^8.2.0",
    "graphql": "^14.5.8",
    "graphql-toolkit": "^0.5.18",
    "graphql-tools": "^4.0.5",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "mongoose": "^5.7.6",
    "nodemailer": "^6.3.1"
  }
```

node version v8.12.0

This is the yarn.lock file for when it works (first dependencies list): https://gist.github.com/acomito/28e15608fcd6675f791ba02c83d36ae7

and this is the error I get with running the second set of dependencies above (with more recent packages)

```
/Users/archer/backend/arrow-backend/node_modules/@graphql-modules/core/node_modules/graphql-toolkit/dist/commonjs/loaders/load-typedefs.js:109
        for await (let path of globby.stream(foundGlobs, { cwd, absolute: true })) {
            ^^^^^

SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Module._extensions..js (module.js:664:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/archer/backend/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Basically, if I do a fresh install in a node project to get accounts-js included, I get this error. e.g. 

`yarn add @accounts/boost @accounts/graphql-api @accounts/mongo @accounts/password @accounts/server @graphql-modules/core apollo-server babel-cli babel-plugin-transform-object-rest-spread babel-preset-env dotenv graphql graphql-toolkit graphql-tools lodash moment mongoose nodemailer`

**Comment by acomito** [comment]
Not sure if it's related to https://github.com/accounts-js/accounts/issues/836

Similar but seems to bubble up from a different package? Maybe a side effect?

**Comment by acomito** [comment]
Ended up just downgrading my versions for now

**Comment by martineboh** [comment]
For Windows users, here is how I FIXED this issue:

1. Add `"preinstall": "npx npm-force-resolutions"` to your package.json file:

`scripts": {
        "start": "meteor run",
        "preinstall": "npx npm-force-resolutions"
    },`

2. Add `"graphql-tools": "^4.0.6",` and `"unique-random-array": "^2.0.0"` to your **dependencies** section in your package.json

3. Include this resolution in your package.json file:

`"resolutions": {
        "graphql-toolkit": "0.5.17-ddafc4c.0"
    },`

4. Run `npm install`

**Comment by acomito** [comment]
I updated to the latest version(s) for accounts server etc and this issue seems resolved
