### ISSUE TITLE
Not able to follow Contributing Docs 

### ISSUE THREAD

**Issue by stolinski** [accounts-js/accounts#850]
https://accounts-js.netlify.com/docs/contributing

Trying to get a local version of this up and running. Follow the steps directly. Upon running `yarn setup`
am seeing this error for each package 
```here's already a package called "@examples/accounts-boost" registered. This command has had no effect. If this command was run in another folder with the same name, the other folder is still linked. Please run yarn unlink in the other folder if you want to register this folder.```

Run `yarn start`

Change into project's directory.

Then, for example, I run `yarn link @accounts/apollo-link` from my project's directory. From there, my project no longer is able to find the `@accounts/apollo-link` module. Am I missing a step here?

**Comment by stolinski** [comment]
I should note that the symlink was created correctly and is pointing to the correct `/accounts/packages/apollo-link-accounts` folder but is unable to find the module.

**Comment by stolinski** [comment]
Looks like the lib folder isn't generated when running `yarn start` from the root of /accounts. I'm not sure if this is intended or not because running `yarn start` from the specific package does create the lib folder.  If this is the intended functionality, I think the solution would be to clarify the docs. If this is the case, I'll submit a pr.

**Comment by stolinski** [comment]
It seems to me like `yarn setup` isn't doing everything it should be doing. It's not properly linking each package together, `yarn start` isn't watching all packages. I've been wrestling with this all morning, any tips on what could be going wrong here would help.

**Comment by stolinski** [comment]
More info. `yarn start` only run yarn start on 5 packages. I'm not sure why though. Here is my console output when running from the root of accounts.

```
$ lerna exec -- yarn start
lerna notice cli v3.16.4
lerna info Executing command in 22 packages: "yarn start"
$ tsc --watch
$ tsc --watch
$ tsc --watch
$ tsc --watch
[11:53:35 AM] Starting compilation in watch mode...
[11:53:35 AM] Starting compilation in watch mode...
[11:53:35 AM] Starting compilation in watch mode...
[11:53:35 AM] Starting compilation in watch mode...

[11:53:43 AM] Found 0 errors. Watching for file changes.

[11:53:44 AM] Found 0 errors. Watching for file changes.

[11:53:44 AM] Found 0 errors. Watching for file changes.

[11:53:44 AM] Found 0 errors. Watching for file changes.
```

**Comment by pradel** [comment]
@stolinski yeah it looks like lerna can't run all the watch command in parallel. you need to run the watch command in the package you are editing I am updating the documentation, thanks for reporting!
