### ISSUE TITLE
Empty Authorization Header gives error

### ISSUE THREAD

**Issue by gbouteiller** [accounts-js/accounts#866]
The current implementation of **@accounts/graphql-client** gives an error with some libraries like **Hasura** because it expects no `Authorization` header or a valid `Authorization` header.  Would it be possible to change : 

**_accounts/packages/graphql-client/src/graphql-client.ts (line 182- line 198)_**
```ts
Authorization: tokens ? 'Bearer ' + tokens.accessToken : '',
```
to something like :
```ts
...tokens ? { Authorization: 'Bearer ' + tokens.accessToken } : {},
```

**Comment by pradel** [comment]
Happy to accept a pr yes 👍
