### ISSUE TITLE
Checking accountsGraphQL.context(req) for an expired access token?

### ISSUE THREAD

**Issue by acomito** [accounts-js/accounts#879]
I have a setup using password + graphql modules.

I start my server with 

```
const server = new ApolloServer({
  resolvers,
  typeDefs,
  context: async req => {

    let result = await accountsGraphQL.context(req);

    if (!result.user) {
      return {
        user: null,
      };
    }

    return {
      ...result,
      user: {
        ...result.user,
      },
    };
  },
});
```

How should I set this up so I can return an error when the auth token has expired? So I can then try and do a token refresh.

```
const server = new ApolloServer({
  resolvers,
  typeDefs,
  context: async req => {
   
    //  maybe check here if token is not included/expired

    let result = await accountsGraphQL.context(req);

    // or check the result here if token has expired

    if (!result.user) {
      return {
        user: null,
      };
    }

    return {
      ...result,
      user: {
        ...result.user,
      },
    };
  },
});
```

**Comment by pradel** [comment]
@acomito if you want to get the raw token you can extract it like this `req.headers['Authorization'].replace('Bearer ', '')` and then check if it's still valid.

I guess the best would be to do that on the client side. I don't know if you use apollo, but if you do you should refresh the token before the call to the server like this https://github.com/accounts-js/accounts/issues/839#issuecomment-575003827

**Comment by pradel** [comment]
Closing this issue, let me know if refreshing the token client-side is not working for you.
