### ISSUE TITLE
Setup autopublish

### ISSUE THREAD

**Issue by TimMikeladze** [accounts-js/accounts#88]
What is everyone's thoughts on having this package (and the rest of the packages) automatically publish to npm whenever new code comes into master? I think this can be setup in the circle config.

**Comment by pradel** [comment]
You mean for example on a @next tag?

**Comment by TimMikeladze** [comment]
Yeah. Or just an actual release. I think if code is in master then it should be published right?

**Comment by pradel** [comment]
I don't really know if we are merging some typo fix etc this doesn't need to have the package pubished again.

**Comment by pradel** [comment]
Is this issue still relevant?

**Comment by davidyaha** [comment]
let's re-open if it ever becomes relevant again
