### ISSUE TITLE
Reduce steps for registering new user and authentication

### ISSUE THREAD

**Issue by nsine** [accounts-js/accounts#891]
Currently to complete "new user" flow with graphql-api of `accounts-js` we have to do 3 steps:
*  `createUser`
* `authenticate`
* `getUser`

Which looks like something we can improve. And there are basically two improvements:
1) autologin user after registration. There is already a draft PR for this https://github.com/accounts-js/accounts/pull/829 which is waiting for adding flag for optional enabling this. I can pick it up
2) add `user` field to `LoginResult` type

And after implementing this we can create user and get his data with one call:
`mutation { createUser(...) }` ->
```
{
  tokens: {...},
  user: { id: 123, ... }
}
```

And ofc "authentication" flow reduces to one call instead of two as well.

Please let me know if this does make sense

**Comment by pradel** [comment]
1. autologin after registration seems like a common request, would be great if we can pass a flag to the server instance and then it will return the session or return the id as it is now (should work for both REST and GraphQL).

I was thinking about something like this `createUser(user: CreateUserInput!): LoginResult | ID` and based on your server configuration one will be returned.

2. I am not sure we want to add the user to the `LoginResult` type since it will add a bit more complexity to the code, you can actually do it in your app yourself by extending the `LoginResult` type no?

**Comment by nsine** [comment]
@pradel regarding 2nd - no complexity actually. I created a PR for this feature - https://github.com/accounts-js/accounts/pull/894

**Comment by nsine** [comment]
@pradel and about autologin - actually i'm thinking of creating separate service method and mutation `createUserAndLogin` because adding flag which affects return-type can cause an issue with graphql-codegen. It will generate types assuming flag `doAutologin = false` (default value), and type of mutation will be `createUser: string`, while in the code it's `createUser: string | LoginResult` which will break typescript compilation.
What do you think?

**Comment by pradel** [comment]
>  It will generate types assuming flag doAutologin = false (default value), and type of mutation will be createUser: string, while in the code it's createUser: string | LoginResult which will break typescript compilation.

I actually don't think so, types should be generated properly for this one :), this will be a breaking change for the graphql schema and needs to also work with rest, so the client types need to be updated :)

Also we should make sure to not allow this option to be true if `ambiguousErrorMessages` is set to true.

**Comment by nsine** [comment]
@pradel how do you imagine gql-schema in such case?
i'd assume `createUser: ID | LoginResult` but that's not possible according to graphql spec.
So generated schema will have either `createUser: ID` or `createUser: LoginResult` type depending on the flag.
And at the moment of schema compilation for codegen it will use this type `createUser: ID`. That's why i said about types incompatibility with codegen. In the resolver anyway we handle both cases and from the resolver we return either ID or LoginResult. However expected type will be only `ID` and typescript will throw an error. I hope that's clear what I mean

So i see several options:
1) forget about types in this specific resolver and return any (i don't like that at all)
2) create new mutation `createUserAndLogin: LoginResult`. This won't break any current code and won't introduce any issues with types (my favorite one)
3) creating new return type for this function
```
type CreateUserAndLoginResult {
userId: String
loginResult: LoginResult
}
``` 
where `loginResult` will be optionally filled if `enableAutologin=true`
- will be a breaking change for frontend users which's not really good

**Comment by pradel** [comment]
@nsine yeah `createUser: ID | LoginResult` will be invalid in graphql you are right, I thought it was possible to do that but looks like it's still an open issue on the graphql repo :D.

Option 3 seems like the best option. There will be other breaking changes on the graphql schema for the next release so now is a good time if we want to add more breaking changes 👍

**Comment by nsine** [comment]
@pradel i opened draft PR for this https://github.com/accounts-js/accounts/pull/901
would appreciate some help with tests covering as don't have too much time to understand how they are organized in the project

**Comment by pradel** [comment]
Pr merged, I will close this issue :)
