### ISSUE TITLE
Improve Accounts config options code

### ISSUE THREAD

**Issue by TimMikeladze** [accounts-js/accounts#9]
The code underneath `AccountsClient.ui.config` can be improved. The provided options object provided as an argument needs to be validated to make sure the user is setting valid keys and values.

Also, write tests :)

**Comment by TimMikeladze** [comment]
@davidyaha Am I correct in saying that since the introduction of Flow into the codebase, as long as we define a type for the config the check for valid keys will happen automatically in consuming code?

**Comment by davidyaha** [comment]
Yeah types will be autocompleted for webstorm or any ide with flow support.
We can add a build step that uses `flow check` to make sure the accounts packages code is consistent with the typings.

This does not mean we can ignore runtime checks where they are necessary..
And also, any user that does not use flow/ts will have no validation what so ever..

**Comment by TimMikeladze** [comment]
Okay, so we still need to include validation for valid keys in the provided options object.
