### ISSUE TITLE
createUser acts incorrectly when user exists in other service (e.g. oauth)

### ISSUE THREAD

**Issue by flashtheman** [accounts-js/accounts#929]
When creating a user using the @accountsPassword client then the server checks whether the user with the given email address already exists. This is fine but the issue is that it should only check if the user exists in the "password" service.

The error message the server returns is "Email already exists".

Example:
Let's say you have 1 "password" users registered and 1 oauth user created (the oauth user is created when logging in for the first time). The issue is that maybe the oauth user now wants to be able to create a "password" service account. The user is not able to do so because the server says the the email already exists.

Suggestion:
Add a flag to AccountServerOptions which allows and disallows the creation of users if he already exists in another service. Maybe oneServicePerEmail: true/false

**Comment by pradel** [comment]
I guess (and I think a lot of apps are doing it that way), that the only way to setup your password if your account was created via OAuth login, would be to be logged in and go in the "settings" page of the app, then call the `changePassword` function where you can setup your password.
So it act more like linking the password service, does it make sense to you?

**Comment by flashtheman** [comment]
Sure fantastic - didn't think of that!. Thanks a lot!!!
